# Tu là phải hiền {- #tu-la-phai-hien}

Buổi nói chuyện hôm nay, tôi nhắm vào Quý Phật tử Phước Thái nhiều hơn là Quý Phật tử ở các nơi. Vậy quý vị hãy lắng nghe cho kỹ. Ở đây, tôi không giảng những đề tài cao siêu mà đặt những câu hỏi rất thực tế, rất thấp, quý vị hãy trả lời đúng như chỗ mình biết, để rồi tôi hướng dẫn cho quý vị tu hành.  
  
\- Quý vị đi chùa học đạo, có phải tu theo đạo Phật không?  
  
\- Thưa phải.  
  
\- Vậy người tu là hiền hay dữ?  
  
\- Dạ hiền.  
  
\- Người đi chùa, lạy Phật, ăn chay, tụng kinh, nếu có người xúc phạm đến thì nóng nảy la lối. Như vậy có hiền không?  
  
\- Dạ chưa hiền.  
  
\- À, chưa hiền tức là chưa tu. Vậy đi chùa tụng kinh mà chưa hiền, chưa gọi là người tu. Người tự nhận mình tu theo đạo Phật mà chưa hiền thì sao? Phải tu thế nào mới gọi là tu theo đạo Phật. Và làm thế nào để được hiền, quý vị biết không?  
  
\- Dạ chưa biết.  
  
\- Đây, tôi hướng dẫn cho quý vị để thành người hiền rất thực tế và dễ dàng. Theo tinh thần đạo Phật, tu là tu ở ba nghiệp: thân nghiệp, khẩu nghiệp và ý nghiệp.  
  
Khi chưa biết tu, thân có khi làm lành, có lúc làm dữ; miệng có khi nói lời thiện, có lúc nói lời ác; ý có khi nghĩ tốt, có lúc nghĩ xấu.  
  
Khi biết tu thì việc lành nên làm, việc dữ nên tránh. Lời thiện thì nói, lời ác thì chừa. Điều tốt thì nghĩ, điều xấu thì dừng. Người biết tu, thân không làm ác, miệng không nói ác, ý không nghĩ ác, đó là người hiền.  
  
Tu chủ yếu không phải ăn chay nhiều. Vậy mà Phật tử cứ đua nhau ăn chay, cho ăn chay nhiều là tu, chứ không biết tu là chừa ba nghiệp ác. Nhân gian có câu ca dao để nhạo báng người ăn chay mà không hiền.  

> Sân si nghiệp chướng không chừa  
> Bo bo mà giữ tương dưa làm gì?  

Tham, sân, si là nghiệp chướng của thân, miệng và ý thì không chịu chừa bỏ, mà cứ đua nhau ăn chay, rồi cho đó là tu. Tu như vậy không đúng với chủ trương của đạo Phật. Tu là thân không làm ác, miệng không nói ác, ý không nghĩ ác.  
  
Trong gia đình, nếu mọi người không biết tu thì cứ cãi và chửi bới gây phiền não cho nhau. Thậm chí, gây cãi không nguôi còn giận thì đánh đập. Đánh đập không thỏa mãn cơn giận thì tình nghĩa không còn. Mà tình nghĩa đã hết thì ly dị chia tay, gia đình đổ nát.  
  
Nếu mọi người biết tu thì ý vừa khởi nghĩ ác liền biết xấu, chế ngự không dám nói lời nặng, không nói nặng thì đâu có cãi, không cãi thì làm gì có đánh đập, không đánh đập thì đâu có ly dị, gia đình thường an vui hạnh phúc.  
  
Như vậy, nếu người biết tu thì ý không bao giờ nghĩ xấu cho ai, tâm không bực bội phiền não, lúc nào cũng vui vẻ an ổn. Nếu ý không nghĩ xấu thì miệng thân đâu có nói làm hung ác khiến cho người đau khổ. Mà không làm khổ người thì được người thương mến, người thương mến thì không hại, nếu có chuyện bất trắc thì được người giúp đỡ.  
  
Khi đã biết tu thì thân, miệng, ý lúc nào cũng thiện. Ba nghiệp mà thiện thì tự thân được an vui, trong gia đình trên thuận dưới hòa, ngoài xã hội không gây xáo trộn sẽ được trật tự an bình. Như vậy, người biết tu, chẳng những chính bản thân mình được lợi ích, mà gia đình và xã hội cũng được lợi ích. Đó là người tu đúng theo lời Phật dạy.  
  
Nếu chỉ biết ăn chay, tay lần tràng hạt, mỗi khi có ai xúc phạm đến thì la lối, chửi rủa không thua ai; người như thế không hiền, chưa phải là người tu. Do vậy, nên bị chế nhạo: *"Ngoài miệng thì nam mô, trong bụng thì chứa một bồ dao găm".*  
  
Ngoài miệng thì niệm Phật lâm râm, nhưng trong tâm thì quá hung dữ. Thế nên, cho ăn chay nhiều, niệm Phật nhiều là tu mà không chịu chuyển thân, miệng, ý cho thiện thì làm trò cười cho thiên hạ. Vì vậy, khi nói tới tu, người Phật tử phải nhớ thân, miệng, ý phải thiện.  
  
Phật dạy, tu một giờ, là được an vui hạnh phúc một giờ, tu một ngày là được an vui hạnh phúc một ngày, tu một năm là được an vui hạnh phúc một năm. Nhưng gần đây, có một số Phật tử nghĩ rằng ăn chay, đi chùa, làm công quả có phước nên ham đua nhau làm.  
  
Ví dụ, trong gia đình, trung bình ăn chay một tháng bốn ngày. Vì nghe nói ăn chay có phước nhiều được khen, nên người vợ tăng thêm sáu ngày, rồi mười ngày... Chồng con ăn theo không nổi nên có chuyện xào xáo trong gia đình. Rồi than trách rằng mình muốn tu, muốn tiến mà bị quỉ nó phá, nó ngăn không cho tu tiến. Người nghĩ nói như vậy có tu không? Tu mà ý khởi nghĩ ác, miệng chửi chồng con là quỉ. Như vậy, chưa phải là người Phật tử chân chính.  
  
Người Phật tử chân chính không đặt nặng việc đi chùa thường xuyên, tụng kinh giỏi, ăn chay nhiều, mà phải biết tu ba nghiệp thân, khẩu, ý cho thiện. Tức là chuyển ba nghiệp ác thành ba nghiệp thiện. Đi chùa, niệm Phật, ăn chay là phải nhớ từng hành động, từng lời nói, từng ý nghĩ luôn luôn phải thiện. Như vậy, có lúc nào là không tu.  

Chẳng hạn, thân cuốc cỏ, xưa thấy rắn thì lấy cuốc đập chết, nay thấy rắn tránh không đập, đó là chuyển nghiệp thân ác thành thiện. Xưa khi tiếp xúc với bạn bè, họ nói lời hung dữ làm mình tức giận, bèn nói nặng lời cho bõ ghét. Nhưng nay nhớ mình là người tu, không được lớn tiếng gây cãi, nên im lặng mà nhẫn nhịn. Đó là chuyển nghiệp khẩu ác thành thiện. Lúc ngồi một mình, vừa khởi nghĩ xấu về người liền hổ thẹn, dừng không nghĩ nữa. Đó là chuyển nghiệp ý ác thành thiện.  

Tu như vậy, đâu có đợi vô chùa tụng kinh lạy Phật mới tu, mà giờ nào, ở đâu tu cũng được. Thế mới đúng ý nghĩa tu của đạo Phật. Nếu hiểu và tu như vậy, thì lo gì mai kia không được về cõi Phật. Trong kinh có câu:  
  
> Tam nghiệp hằng thanh tịnh  
> Đồng Phật vãng Tây phương  
  
Ba nghiệp mà hằng trong sạch thì đồng với Phật, về cõi Phật. Nếu không bỏ ba nghiệp ác mà cố niệm Phật nhiều, cầu Phật A-Di-Dà rước về Cực Lạc, cũng không được rước về. Vì ba nghiệp còn ác thì về đó cứ gây cãi, đánh đập hoài biến cõi Cực Lạc thành cõi Ta Bà khổ hay sao?  
  
Vậy, tu cốt là chuyển ba nghiệp ác thành ba nghiệp thiện là bước đầu, tụng kinh niệm Phật là bước kế tiếp. Bước đầu là nền tảng mà không thực hiện trước, lại đi bước thứ hai, giống như cất nhà lầu mà không xây nền móng, nhất định cái nhà sẽ đổ không thành.  
  
Lại cũng có nhiều Phật tử đi chùa lâu năm, ăn chay, niệm Phật, nếu con cháu có làm gì phật ý thì mắng chửi không tiếc lời, khiến cho con cháu buồn không thương mến. Rồi viện cớ là chỉ hiền với người ngoài thôi, đối với con cháu trong nhà phải khó, phải dữ nó mới sợ. Người Phật tử nói vậy là không đúng. Tu là phải hiền, hiền với tất cả mọi người, từ trong nhà cho đến ngoài xã hội. Giả sử con cháu có làm bậy, làm sai, thì nên ôn tồn nhỏ nhẹ khuyên dạy con cháu. Đừng nên chửi bới la rầy, vì lúc nóng giận không kiểm soát được ý nghĩ, lời nói, sẽ nói bậy. Mà nói bậy thì mất uy tín với con cháu.  
  

Kinh Phật ví dụ một Trưởng giả có tất cả bốn bà vợ. Người thứ nhất rất trung thành với ông, thế mà suốt ngày ông không nghĩ tới. Người vợ thứ hai được ông lưu ý chút ít. Người vợ thứ ba được ông nhắc nhở liền miệng. Người vợ thứ tư thì ông ở đâu bà có mặt ở nơi đó, không rời một gang tấc. Một hôm ông đau nặng sắp chết, hỏi cả bốn người vợ:  
  
\- Tôi sắp chết, trong bốn bà có ai nguyện chết theo tôi không?  
  
Vợ thứ tư lên tiếng trước:  
  
\- Bình thường ông ở đâu thì có mặt tôi ở đó. Bây giờ ông chết, tôi xin đưa ông tới cửa.  
  
Vợ thứ ba lên tiếng tiếp:  
  
\- Bình thường tôi được ông lưu ý nhắc nhở liền miệng. Bây giờ ông chết, tôi xin đưa ông tới cổng.  
  
Vợ thứ hai nói:  
  
\- Bình thường tôi cũng được ông nhắc nhở. Bây giờ ông chết, tôi xin đưa ông tới mộ.  
  
Vợ thứ nhất nói:  
  
\- Bình thường tuy ông không nghĩ tới, nhưng bây giờ ông chết, tôi nguyện chết theo ông.  
  
Quý vị thấy ông Trưởng giả quá bất công và bội bạc. Người thương mình, trung thành với mình thì lơ là không nghĩ đến. Người thương ít thì luôn luôn theo dõi không rời. Ông Trưởng giả bất công bội bạc này, Phật dụ cho mỗi người chúng ta.  
  
Người vợ thứ tư, Phật dụ cho tiền bạc. Chúng ta ở nhà hay đi đâu đều có tiền trong túi không thể thiếu nó. Nhưng khi chúng ta chết thì nó nằm trong tủ hoặc ở nơi rương thuộc phạm vi trong nhà. Vì vậy mà nói đưa tới cửa.  
  
Người vợ thứ ba dụ cho của cải sự nghiệp, nhà cửa. Nó nằm ở trong phạm vi vòng rào nhà, nên nói đưa tới cổng.  
  
Người vợ thứ hai dụ cho công danh, chức tước. Khi đưa quan tài người chết tới huyệt thì đọc điếu văn kể công trạng rồi mới hạ huyệt chôn cất, nên nói đưa tới mộ.  

Người vợ thứ nhất dụ cho nghiệp lành hay nghiệp dữ theo mình như hình với bóng. Có mình ở đâu thì có nó ở đó không rời nhau, nên mới tình nguyện chết theo.  
  
Tác động của thân, khẩu, ý lặp tới lặp lui nhiều lần gọi là nghiệp. Người dạy học hằng ngày thì gọi là nghề giáo hay nghiệp giáo. Người cùng làm một việc thì gọi là bạn đồng nghiệp. Có người là có nghiệp. Người nghiệp không rời nhau.  
  
Giả sử như ông thầy giáo đi đường có mang theo một số tiền của. Bất thần ông bị tai nạn, bao nhiêu tiền ông mang theo bị mất hết. Nhưng nghiệp dạy học vẫn còn không mất, về nhà vẫn đến trường dạy học trò. Như vậy, tiền của và tài sản là cái ngoài mình nên bị mất dễ dàng, không thể giữ được mãi mãi. Còn nghiệp là cái không ngoài mình nên chẳng bao giờ mất. Thế mà trong cuộc sống hằng ngày, mọi người đều nghĩ làm sao cho có tiền, làm sao cho có của. Nếu có tiền, có của rồi thì muốn có địa vị, danh vọng. Trong ba thứ đó, nghĩ tới tiền nhiều nhất, rồi tới của cải, danh vọng. Khi chết, thì tiền của từ giã mình trước nhất, tức là khi chết nó ở lại chứ không theo mình.  
  
Trong đời này không ai là (người) không chết. Hoặc chết sớm, hoặc chết muộn. Khi chết thì không ai đem được tiền của theo, chỉ có nghiệp lành hay nghiệp dữ theo mà thôi. Thế nên, nếu là người Phật tử khôn ngoan sáng suốt, dù có làm ra nhiều tiền của mà làm ác thì nhất định không làm. Vì khi chết không cứu được tội khổ mà phải để lại tất cả, chỉ có một mình mình chịu quả báo khổ đau. Nghĩ và nói ác mà đem lại lợi lộc cho mình thì cũng không nói. Như thế không bị tiền tài sai sử tạo nghiệp ác.  

Ngày nay không gây tạo tội lỗi, không bị người chê trách, mai kia chết đi cũng nhẹ nhàng thảnh thơi. Ca dao có câu:  
  
> Bởi chừng kiếp trước khéo tu,  
> Ngày nay con cái võng dù nghênh ngang  
  
Do kiếp trước khéo tu nên ngày nay con cháu mới sang trọng. Nếu hiện tại không chịu tu thì con cháu về sau khổ. Để thấy chúng ta tu là tạo cho cuộc sống hiện tại an vui, ngày mai lại càng an vui tốt đẹp hơn. Vậy, biết tu là thường nhớ tới nghiệp, để tránh nghiệp ác, làm nghiệp lành, hơn là nhớ tới tiền của, vật chất. Tuy trong cuộc sống, chúng ta phải làm ra tiền mới sống được, nhưng phải làm cho công bằng lương thiện. Mình an vui, người không khổ, hiện tại mình hạnh phúc, mai sau cũng an lành. Vậy, tu không phải là mong cầu cái gì cao siêu huyền bí, mà ngay trong thực tế thường làm lợi mình, lợi người một cách cụ thể, không mơ hồ viễn vông.  
  
Đạo Phật chủ trương tu là để giải thoát, song nói giải thoát có vẻ xa vời quá! Nhưng nếu thực tế, thân chúng ta không làm ác là giải thoát được cái khổ nghiệp ác của thân. Vì nếu cướp của giết người thì bị cái khổ đánh đập tù tội. Bây giờ không tạo nghiệp ác ấy thì thân được lành mạnh tự do, đó là giải thoát nghiệp ác của thân.  
  
Nếu miệng không nói lời hung dữ ác độc thì giải thoát được nghiệp ác của miệng. Ý không nghĩ ác thì giải thoát được tâm niệm xấu xa, buồn ghét người khác. Tuy không hoàn toàn giải thoát nhưng có giải thoát từng phần. Tu ít thì giải thoát ít, tu nhiều thì giải thoát nhiều, có tu là có bớt khổ. Chẳng những bớt khổ trong đời này mà trong đời sau còn được an vui nữa. Nên người biết tu không sợ chết. Vì ai cũng phải chết, và biết rằng mình không tạo nghiệp ác thường tạo nghiệp lành, sau khi chết sẽ an vui chớ không khổ. Tuy nhiên, đừng vì muốn giải thoát mà liều chết sớm để được khỏe được sướng thì không đúng với tinh thần giải thoát của đạo Phật.  
  
Thông thường thì người đời tham sống sợ chết, nên nghe nói chết thì rất sợ. Nhưng người biết tu thì ngay cuộc sống hiện tại lúc nào cũng an vui, khi chết đến thì bình thản không loạn động, nên không muốn chết sớm mà cũng không sợ chết. Vì vậy mà Phật tổ mới dạy chúng ta tu, tu là nguồn cội hạnh phúc, hết phiền não, hết khổ đau.  
  
Kể từ ngày nay, quý Phật tử ở gần thiền viện, mỗi tháng hai lần vào ngày rằm và ba mươi nên đi chùa sám hối và nghe quý thầy giảng để biết phương hướng mà tu tập. Nghe một lần tuy biết đó, nhưng vì cái bệnh chúng sanh hay quên, nên mỗi tháng phải đi hai lần, nhờ các thầy nhắc nhở, luôn ghi nhớ mới tinh tấn mà tu hành.  
