# Nghiệp dẫn đi trong luân hồi lục đạo {- #nghiep-dan-di-trong-luan-hoi-luc-dao}
  
Giáo lý của nhà Phật cốt yếu dạy cho con người tu để giải thoát luân hồi sanh tử. Tuy nhiên, tùy theo sức huân tu cao thấp mà giải thoát cũng có nhiều từng bậc. Đại lược chúng ta có thể chia làm hai bậc là: Từng phần giải thoát và toàn phần giải thoát.  
  
Từng phần giải thoát là bậc thứ nhất, tu mà còn luân hồi sanh tử, nhưng biết chọn lựa phước lành để đi trong đường tốt hưởng phước báo. Những loại chúng sanh đi trong các đường địa ngục, ngạ quỉ, súc sanh, A-tu-la đều không biết chọn nghiệp lành nên đi vào con đường ác, chịu quả báo khổ đau. Và ngay như loài người có biết chọn nghiệp thiện, lại cũng có người không biết chọn nên tạo lắm nghiệp ác. Vì vậy mà chịu không biết bao nhiêu thứ khổ đau.  
  
Thế nên, khi còn ở trong lục đạo luân hồi, sau khi bỏ thân này, muốn cho đời sống của thân sau được an vui hạnh phúc thì ngay hiện tại phải biết chọn lựa nghiệp lành để làm và để tránh ba nghiệp ác, đó là gốc của sự tu hành.  
  
Nghiệp là động lực dẫn chúng ta đi trong luân hồi sanh tử, nên rất hệ trọng đối với sự tu hành. Vậy nghiệp là gì? Nghiệp được dịch từ chữ Phạn Karma nghĩa là hành động lặp đi lặp lại nhiều lần thành thói quen. Thói quen đó gọi là nghiệp.  
  
Ví dụ giáo viên dạy học, dạy từ năm này qua năm khác, được gọi là nghề giáo và những người làm cùng nghề thì gọi là bạn đồng nghiệp.  
  
Nghiệp là việc làm của chính mình, mình làm chủ và tạo tác thành thói quen, rồi cũng chính mình thừa nhận hậu quả do nó đưa tới. Kinh Phật dạy: *"Chúng sanh làm chủ tạo nghiệp và thừa kế cái nghiệp do chính mình đã tạo"*. Không do ai khác ngoài mình.  
  
Chúng ta từ thuở sơ sinh cho tới chín, mười tuổi đâu có ai mắc bệnh ghiền rượu, ghiền trầu hay ghiền thuốc... Thế mà từ 15, 16 tuổi cho tới già, do sự tập tành thành thói quen, người thì ghiền rượu, người thì ghiền thuốc, kẻ thì ghiền á phiện...  
  
Đứa trẻ 15, 16 tuổi thấy người lớn cầm thuốc hút nhả khói phì phà tưởng đó là oai là sang, nên bắt chước hút, thành thói quen rồi ghiền thuốc. Lúc mới tập hút thì mình làm chủ, thích hút thì hút, không thích hút thì thôi. Nhưng hút nhiều lần dần dần thành thói quen, thiếu thuốc thì khó chịu, ngáp, buồn, phải đi mua về hút. Vậy khi đã ghiền rồi thì không còn làm chủ nữa mà nó làm chủ ngược lại mình, sai sử mình làm theo thói quen ưa thích đó. Vậy, nghiệp là cái chúng ta tự tạo, chúng ta làm chủ tạo thành thói quen. Khi thói quen thuần thục thì nó làm chủ dẫn dắt sai sử chúng ta.  
  
Nếu ta tập thói quen làm việc thiện thì được dẫn dắt tiếp tục làm việc thiện. Nếu chúng ta tập thói quen làm việc bất thiện thì bị dẫn dắt tiếp tục làm việc bất thiện.  

Chẳng hạn, người mỗi chiều đi chùa tụng kinh lâu ngày thành thói quen. Một hôm, tới giờ tụng kinh không đi cảm thấy thiếu, thấy buồn, có một động lực thôi thúc bắt phải đi chùa tụng kinh.  
  
Còn người khác, mỗi chiều đi quán uống rượu, lâu ngày thành thói quen nên ghiền. Tới cữ đi uống rượu, không đi thì cảm thấy bức rức khó chịu, ngáp dài, có một ma lực thôi thúc sai khiến tới quán rượu để uống rượu.  

Người đi chùa tụng kinh tập thành thói quen đó là nghiệp thiện, đưa tới sự an vui lợi ích cho bản thân mình. Người đi quán uống rượu tập thành thói quen là nghiệp ác, đưa tới nghèo thiếu, bệnh hoạn, kém trí tuệ.  

Vậy, nghiệp phát xuất từ đâu? Nếu thân tạo tác thiện đó là nghiệp thiện của thân, thân tạo tác ác đó là nghiệp ác của thân. Miệng nói điều lành là nghiệp thiện của miệng, miệng nói lời hung dữ là nghiệp ác của miệng. Ý nghĩ tốt là nghiệp thiện của ý, ý nghĩ xấu là nghiệp ác của ý. Đó là nghiệp phát xuất từ thân, khẩu, ý.  
  
Như vậy, tạo nghiệp chủ động là mình. Nếu muốn luân hồi chỗ tốt, cho thân lành mạnh tốt đẹp, được sống an vui hạnh phúc thì hiện tại phải biết tạo nghiệp thiện. Nếu ngược lại, tạo nghiệp ác thì luân hồi đến cõi xấu, thọ thân xấu, sống đời đầy đau khổ. Do mình chủ động trọn vẹn, chớ không do ai khác. Ngay trời Phật cũng không dự phần trong đó.  

Như vậy, chúng ta là chủ chọn lấy hướng đi cho chúng ta mai sau. Nếu khôn ngoan đã chọn cho mình một hướng đi tốt đẹp thì cứ theo hướng đó mà đi, chớ có thay đổi.  
  
Cũng như các học sinh sau khi đã chọn nghề và tốt nghiệp ra trường, phải theo cái nghề mình đã chọn mà sống. Sướng hay khổ tùy theo cái nghề của mình chọn.  
  
Vậy, chúng ta tu là phải làm sao? Có nhiều Phật tử than vì bệnh tật, vì nghèo khổ không thể tu. Người than như vậy là chưa biết tu, vì họ tưởng phải đi chùa nhiều, tụng kinh giỏi mới là tu. Như đã nói, tu là chuyển nghiệp ác thành nghiệp thiện, mà nghiệp thì phát xuất từ thân, khẩu, ý.  
  
Giả sử như người buôn bán, nếu tráo hàng thật ra hàng giả, hoặc cân đo thiếu, hoặc bán người trả giá không đúng, nổi giận la chửi, đó là thân miệng tạo nghiệp ác, không biết tu.  
  
Nếu buôn bán với mức lời vừa phải, hàng thật nói là hàng thật, hàng giả nói là hàng giả, cân đo đúng, khách trả đúng giá thì vui vẻ bán, khách trả không đúng giá tuy không bán vẫn vui cười, không tức giận mắng chửi.  
  
Hoặc đi đường gặp người già yếu nhường lối đi, nhường chỗ ngồi, đưa qua đưòng, đưa qua cầu, bưng xách nặng dùm người... đó là thân khẩu thiện, biết tu. Tu trong công ăn việc làm, tu ngoài đường, tu ngoài chợ.  
  
Ở trong nhà, đối với người thân cũng phải giữ thân miệng luôn lành. Làm cha mẹ giữ đúng tư cách của cha mẹ, con cái có lỗi lầm phải từ tốn răn dạy, hướng dẫn phù hợp với đạo lý cho con nên người, đó là tu. Nếu ỷ quyền cha mẹ, khi con làm không vừa ý, tay đánh đập, miệng la hét, chửi rủa, đó là không biết tu. Phận làm con đối với cha mẹ phải biết thương kính, chăm lo việc ăn mặc thuốc thang cho cha mẹ, đừng để cha mẹ buồn tủi lúc tuổi già. Nếu cha mẹ có sanh tật khó khăn thì nên an ủi khuyên lơn hơn là hờn trách chế diễu. Đó là chuyển nghiệp thân, nghiệp khẩu luôn lành.  
  
Về ý nghiệp có phần vi tế hơn, với người biết tu cũng chuyển được nghiệp ác thành nghiệp thiện. Nếu đang ngồi chơi hay đi, hoặc làm việc, khởi nghĩ buồn giận người, biết đó là ác ý liền dừng không nghĩ, mà khởi nghĩ thương người nghèo khó, quý kính bậc hiền đức, tìm cách giúp đỡ người khốn khổ... Đó là chuyển nghiệp ý ác thành ý thiện.  
  
Nếu cho rằng đi chùa hay tụng kinh mới là tu, thì tu quá ít. Rồi bệnh nào tật ấy vẫn còn nguyên. Tham, sân, si, ích kỷ vẫn không chừa, tu như thế hiện tại tự mình không lợi ích và cũng không đem được an hòa cho mọi người chung quanh, mai sau bị nghiệp lôi vào đường ác là địa ngục, ngạ quỉ, súc sanh.  
  
Thế nên, Phật dạy trong tất cả ngày giờ của mọi sinh hoạt đều phải tu mới chuyển được ba nghiệp trọn lành. Ba nghiệp lành rồi, ngay đời hiện tại tự mình không phiền não, lúc nào cũng nhẹ nhàng an vui. Trong gia đình mọi người không thắc mắc rày rà, trên thuận dưới hòa, đầm ấm hạnh phúc. Ngoài xã hội được an bình, không loạn ly. Tu như thế mới thật là tu. Đừng vì muốn được đi chùa thường xuyên, muốn được tụng kinh nhiều mà phế bỏ cả việc nhà. Thân, miệng, ý không chuyển cho lành, về nhà thì thắc mắc, gây cãi hết người này tới người nọ làm cho gia đình xào xáo. Đối với người ngoài xã hội thì không nhịn một lời, không nhượng một bước. Đi chùa tụng kinh như thế là chưa thật tu.  
  
Có một bà cụ Nhật Bản lần chuỗi niệm Phật rất giỏi. Khi lần chuỗi niệm Phật thì rất chăm chỉ, nhưng khi dừng niệm Phật thì rầy rà con cháu inh ỏi. Con trai bà thấy bà tu như thế nó buồn và nói:  
  
\- Má à, má tu má cứ lo niệm Phật đi, sao má cứ rầy rà hoài khiến xao lãng làm sao Phật chứng cho má?  
  
Bà nói:  
  
\- Khi nào tao niệm Phật thì Phật thông cảm cho tao, còn khi nào tao rầy tụi bây thì tụi bây biết cho tao.  
  
Bà chia làm hai phần, phần niệm Phật thì tu với Phật, phần rầy la thì dành cho con cháu! Người thật tu là vừa tu với Phật cũng vừa tu với thế gian, tu như thế mới trọn vẹn.  
  
Có người ngoại đạo đến hỏi Phật:  
  
\- Thưa ngài Cồ Đàm *(họ Gautama, tên Siddhartha dòng Shakya, của Đức Phật Thích-Ca)*, cái gì định đặt cho con người, sinh ra kẻ thì nghèo nàn khổ sở, người thì giàu sang sung sướng, kẻ thì sống lâu, người thì chết yểu, kẻ thì yếu đau, người thì khỏe mạnh, kẻ thì ngu dốt, người thì thông minh?  
  
Phật trả lời:  
  
\- Tất cả sự sai biệt giữa con người và con người là do nghiệp mà họ đã tạo định đặt ra, nên có người ưu, kẻ liệt.  
  
\- Do tạo nghiệp gì khiến cho con người sống lâu và do tạo nghiệp gì khiến cho người chết yểu?  
  
\- Người không tạo nghiệp sát hại chúng sanh thì được thọ mạng lâu dài. Người tạo nghiệp sát, đoản mạng sống của chúng sanh nên thọ mạng yểu.  
  
\- Do tạo nghiệp gì thân người được khoẻ mạnh và do tạo nghiệp gì mà thân hay yếu đau bệnh tật?  
  
\- Do nghiệp ác làm cho người đau khổ nên thọ thân hay bệnh tật đau yếu. Và do nghiệp lành an ủi giúp đỡ người qua những tai nạn khốn khó nên được thọ thân khỏe mạnh vui tươi.  
  
\- Do tạo nghiệp gì mà sinh thân trong gia đình giàu sang sung sướng và do tạo nghiệp gì mà sinh thân trong gia đình nghèo khó khốn khổ?  
  
\- Do đời trước biết làm lành, biết bố thí cúng dường, biết giúp đỡ người nghèo khó bệnh tật, nên đời này được sinh ra trong cảnh giàu sang sung sướng. Người ở đời trước không biết bố thí cúng dường, không biết giúp đỡ người nghèo khó, lại còn tham lam rút rỉa của người nên đời này sanh thân trong cảnh nghèo đói thiếu thốn.  
  
\- Do nghiệp gì người sanh ra được thông minh sáng suốt và do nghiệp gì người sanh ra lại ngu dốt tối tăm?  
  
\- Người đời trước do siêng năng học hỏi tìm hiểu chân lý, ưa thích giúp người được học hỏi hiểu biết nên đời này được thông minh. Người ở đời trước do lười biếng học, không chịu tìm hiểu chân lý, cản ngăn sự học hỏi của người nên đời này bị tối tăm mê mờ.  
  
Vậy, tất cả quả tốt hay xấu mà chúng ta đang thọ hiện nay, gốc là từ cái nhân chúng ta gây thuở trước, chứ không phải bỗng dưng mà có. Khi đã biết như thế, chúng ta muốn ngày mai được tốt đẹp an vui hay bị đau khổ, thì ngay bây giờ chúng ta phải chuẩn bị.  
  
Nếu chuẩn bị bằng nghiệp lành thì sẽ được đến cõi lành và được an vui hạnh phúc. Nếu chuẩn bị bằng nghiệp ác thì sẽ đi vào đường dữ và bị khổ đau.  
  
Có người nêu nghi vấn: Hiện tại thân này hành động tạo nghiệp thiện hay ác, mai kia thân hoại rồi hành động cũng mất, vậy nghiệp còn hay mất? Đa số người không tin nhân quả, họ nghĩ rằng sau khi thân hoại hành động cũng không còn thì nghiệp cũng mất.  
  
Trong kinh Phật thường nói nghiệp theo mình như bóng với hình vậy. Đời quá khứ, đời hiện tại, đời vị lai có sự liên hệ tùy theo nghiệp của mỗi người.  
  
Ví dụ, có hai người khách qua sông, một người chuyên nghề giáo, một người chuyên nghề thương mãi. Khi đi đường người thương mãi đem theo nhiều vàng bạc của cải, nhà giáo chỉ mang theo một cặp sách vở và chút ít tiền lộ phí. Thuyền qua giữa sông bất thần gặp sóng làm chìm. Khi thuyền chìm, mạnh ai nấy lo, lội vào bờ để thoát chết. Lên đến bờ thì tất cả của cải, tiền bạc của nhà thương mãi không còn, cặp giấy tờ, tiền lộ phí của nhà giáo cũng mất. Cả hai đều trắng tay, nhưng kiến thức giáo dục của nhà giáo không mất, kiến thức mua bán của nhà thương mãi cũng không mất. Kiến thức là cái chuyên môn sở trường của con người không mất, tức là nghề nghiệp không mất.  
  
Như vậy, để thấy, qua những cuộc biến đổi, tất cả những cái có hình tướng ngoài mình thì mất. Nên khi thân này có hoại đi, nghiệp thức không ngoài mình nên không mất. Của cải tài sản thế gian, chúng ta tạo sắm nhiều thế mấy, khi chết rồi tất cả đều phải để lại, không đem theo được một món nào, chỉ có mang theo nghiệp mà thôi. Đó là một lẽ thật. Thế mà, có nhiều người không hiểu không tin, rồi mê tín dán nhà lầu xe hơi, mua giấy tiền vàng bạc đốt để đem theo cho cha mẹ chồng con chết xài.  
  
Có người vội hỏi:  
  
\- Con cháu vì thương cha mẹ, sau khi cha mẹ chết họ dán nhà, xe, mua giấy tiền vàng thật nhiều đem đốt và cầu nguyện cho cha mẹ được hưởng. Như vậy, cha mẹ có được hưởng không?  
  
\- Nếu con cháu đốt giấy tiền vàng bạc rồi cầu nguyện cho cha mẹ lãnh, tôi e rằng ở tù chớ chẳng được hưởng. Tại sao? Vì mang bạc giả xuống diêm vương xài là bất hợp pháp. Nếu đốt nhà lầu xe hơi giấy, cầu cho thân nhân mình lãnh về ở và đi, tôi cho rằng nếu ai làm như vậy là hại thân nhân của mình. Vì nếu họ nhận được thì họ có nhà lầu để ở, có xe hơi để đi, có tiền bạc để xài, đủ tiện nghi quá thì họ sẽ ở mãi cõi âm, không đi đầu thai. Đó là trường hợp thân nhân của mình trong sanh tiền có chút phước lành.  
  
Còn nếu là kẻ có tội thì chết đọa địa ngục bị giam nhốt hành hạ làm sao mà nhận lãnh tiền bạc nhà xe để xài? Đó là chưa nói đến nhà xe tiền bạc bị đốt thành tro thì dùng làm sao được? Thật là vô lý!  
  
Như vậy, để thấy chính nghiệp lành hay dữ mà mình tạo ra nó dẫn mình đi thọ thân trong cảnh giới sướng hay khổ. Tất cả việc làm bên ngoài của người thân vì thương muốn giúp mình khó mà giúp được, mình làm mình phải chịu, người khác không thể thế được.  
  
Lại có người nêu câu hỏi:  
  
\- Tại sao có nhiều người làm ác mà họ sống phây phây? Có nhiều người rất hiền lành, làm phước, làm nghĩa mà lại gặp nhiều hoạn nạn. Như vậy là luật nhân quả bất công sao? Lại có nhiều người không làm ác, vừa làm ác thọ quả báo liền, hoặc vừa làm thiện thì thọ quả báo lành liền. Như vậy là sao?  
  
Trong kinh Phật có dạy: Nếu tạo nghiệp thiện được phước báo lành, tạo nghiệp ác bị quả báo khổ thì Phật chấp nhận. Nếu nói rằng làm nghiệp thiện sau khi chết sẽ sanh về cõi Trời, làm nghiệp ác sau khi chết sẽ đọa xuống địa ngục liền, điều đó Phật không chấp nhận.  

Tại sao nói làm ác chịu chịu quả báo ác, làm thiện được quả báo thiện, thì Phật chấp nhận. Mà nói tạo nghiệp ác sau khi chết đọa địa ngục, làm lành sau khi chết về cõi Trời thì Phật không chấp nhận?  

Về thuyết nghiệp, Phật có nói cận tử nghiệp và tích luỹ nghiệp. Tích lũy nghiệp chứa từ nhiều kiếp đến giờ. Cận tử nghiệp là nghiệp mới tạo tác lúc sắp chết. Cận tử nghiệp và tích lũy nghiệp có ảnh hưởng chi phối nhau mà quyết định đưa người chết đến cõi lành hay cõi dữ.  
  
Ví dụ, có người tích lũy nghiệp lành từ xưa đến nay, bất thần họ mê muội có người xúi dục họ làm điều ác. Làm điều ác này đáng lý phải đọa địa ngục, nhưng vì tích lũy nghiệp lành họ còn nhiều nên chưa đọa địa ngục liền.  
  
Lại cũng có người làm nhiều điều ác, đáng lý phải đọa địa ngục, nhưng gần chết họ làm lành, tâm họ luôn nghĩ tưởng đến điều lành nên không đọa địa ngục. Thế nên, nói làm ác khi chết nhất định đọa địa ngục, làm thiện lên thiên đàng, thì không đúng hẳn. Vì tuy họ có làm ác, nhưng lúc gần chết, cận tử nghiệp thiện họ quá mạnh có thể đưa họ đến cõi thiện.  
  
Còn người tuy làm nhiều điều thiện, nhưng khi gần chết họ nổi sân quá hung dữ. Lúc đó, cận tử nghiệp ác có thể đưa họ đến các đường xấu. Thế nên, không phải chỉ tu khi sắp chết, hoặc chỉ tu ở giai đoạn thân còn mạnh khỏe mà phải luôn luôn giữ thân, khẩu, ý lành, từ lúc còn trẻ trung mạnh khỏe cho đến chung cuộc của kiếp người.  
  
Xưa có Maha Nam, con của Cam Lộ Phạm Vương, em nhà chú của Đức Phật. Maha Nam tu cư sĩ, giữ năm giới, tu thập thiện, thọ bát quan trai... Một hôm hỏi Phật rằng:  
  
\- Bạch Thế Tôn, bình thường con tu giữ năm giới, thọ bát quan trai, tu thập thiện. Giả sử con chết bất đắc kỳ tử bởi một tai nạn xảy ra, sau khi chết con sẽ đi về đâu?  
  
Phật trả lời bằng một ví dụ:  
  
\- Có một cây mọc từ đất lên, thân và cành cây nghiêng về một bên. Vậy khi cưa, thân ngã về bên nào?  
  
Maha Nam đáp:  
  
\- Cây ngã về phía mà nó đang nghiêng.  
  
Phật dạy tiếp:  
  
\- Cũng vậy, bình thường ông hay làm điều lành, khi chết tuy bị khủng hoảng, nhưng nghiệp thiện tích lũy nhiều sẽ hướng ông đến chỗ lành. Không sao, đừng sợ.  
  
Vậy, chủ yếu của việc tu hành, chẳng những tạo nghiệp lành trong lúc còn mạnh khỏe mà lúc gần chết tâm niệm cũng phải lành thì mới bảo đảm đi đến cõi lành. Và bình thường tạo nghiệp lành, mà lúc gần chết tạo nghiệp dữ thì chưa bảo đảm đi đến cõi lành. Và bình thường nếu lỡ làm ác, lúc gần chết tâm niệm lành thì cũng chuyển được phần nào nghiệp dữ, vì nghiệp không cố định.  
  
Để kết thúc buổi nói chuyện hôm nay, tôi nhắc lại câu chuyện Lý Bạch đời Đường ở Trung Hoa. Ông là một nhà thơ nổi tiếng, nghe danh Thiền Sư Ô Sào là một cao tăng đắc đạo mới tìm tới tham vấn. Tới nơi, thấy Thiền Sư Ô Sào ngồi trên cháng ba của một cây cổ thụ. Chỗ ngài ở giống như một ổ quạ nên người đời gọi Ngài là Thiền Sư Ô Sào. Ông đứng dưới đất nhìn lên hỏi:  
  
\- Bạch Hòa Thượng, Xin Hòa Thượng dạy cho tôi một phương pháp tu ngắn và gọn để tôi có thể tu được.  
  
Thiền Sư Ô Sào ở trên nói xuống:  
  
> Chư ác mạc tác  
> Chúng thiện phụng hành  
> Tự tịnh ká ý  
> Thị chư Phật giáo  
  
Ông hãy về tu đi!  
  
Lý Bạch nghe qua, cười và nói:  
  
\- Hòa Thượng nói bài kệ đó con nít tám tuổi cũng thuộc, vậy Hòa Thượng đem dạy tôi để làm gì?  
  
Thiền Sư Ô Sào nói:  
  
\- Phải, con nít tám tuổi cũng thuộc nhưng ông già tám mươi tuổi làm cũng chưa xong.  
  
*"Chư ác mạc tác"* là tất cả nghiệp ác chớ có làm.  
  
*"Chúng thiện phụng hành"* là vâng làm tất cả các nghiệp lành.  
  
*"Tự tịnh ká ý"* là khéo lóng lặng tâm cho thanh tịnh.  
  
*"Thị chư Phật giáo"* đó là lời dạy của chư Phật.  
  
Tu cốt là bỏ nghiệp ác của thân, khẩu, ý và chuyển thành nghiệp lành. Bài kệ trên vừa nghe qua là dễ nhớ và dường như thấy dễ làm. Song, đi vào kinh nghiệm tu hành thì không đơn giản và dễ dàng vì tình thức mênh mang, chủng tử tập khí sâu dày, vừa bỏ được thói xấu này để phát huy điều tốt nọ, thì lại có dư tập dở khác đang ngủ ngầm hội đủ duyên nó trổi dậy lại phải điều phục nữa. Và cứ thế làm mãi cho đến chung cuộc của kiếp người, có khi chưa xong, tâm vẫn còn lao xao, lộn xộn.  

Thế nên, người biết hướng thiện luôn luôn phải xoay lại mình để lo tu tập, ở trong mọi hoàn cảnh, trong mọi trường hợp. Người rỗi rảnh hay bận rộn, giàu sang hay nghèo hèn ai cũng tu được. Điều tiên quyết là dừng nghiệp ác, rồi tùy theo hoàn cảnh: người nghèo thì ra công sức giúp đỡ, kẻ giàu thì ra tiền của bố thí. Ai ai cũng biết tu thì tự mình được an vui, gia đình được hạnh phúc, xã hội được an bình. Tu chính là nền tảng vững chắc để xây dựng cuộc đời hiện tại được tươi đẹp và tạo cơ hội cho đời sau càng được an vui, sáng suốt hơn.  
  
Vậy, từ đây về sau trọn đời, quí Phật tử cố gắng tránh tất cả các điều ác, làm tất cả các nghiệp lành. Làm đó là làm cho chính mình chớ không phải làm cho ai khác. Đạo Phật được coi là đạo cứu khổ ban vui. Mà cứu khổ ban vui là chỉ cho mọi người con đường nào đi đến khổ đau và con đường nào đi đến an lạc. Khi biết con đường đưa tới an lạc thì cố gắng đi, đó là đạo Phật cứu khổ ban vui cho quý vị. Còn nếu quý vị biết con đường thiện đưa tới an lạc, con đường ác đưa tới khổ đau mà cứ đi con đường đau khổ thì đó là tại quý vị không biết chọn đường đi, khổ là do mình chớ không do ai khác. Vì Phật đã vạch lối chỉ đường rất rõ ràng, nếu chọn và thực hành đúng lời Phật dạy thì được an vui, lợi ích, ngược lại thì khổ đau. Đó là then chốt mà quý vị phải biết rõ và nắm vững để tu hành.  
