# Biệt nghiệp và đồng nghiệp {- #biet-nghiep-va-dong-nghiep}
  
Nghiệp là thói quen huân tập tạo thành sức mạnh chi phối tất cả mọi sinh hoạt trong cuộc sống của con người từ khi mở mắt chào đời cho đến khi nhắm mắt và những đời kế tiếp. Nếu người Phật tử tu mà không hiểu rõ về nghiệp thì khó mà ứng dụng tu hành để tới chỗ an lạc. Chữ nghiệp trong nhà Phật không có nghĩa một chiều, hễ nói nghiệp thì phải là điều xấu, điều ác. Kỳ thật, nghiệp cũng có xấu và cũng có tốt, nghiệp cũng có nghiệp chung và nghiệp riêng. Nghiệp riêng thì gọi là biệt nghiệp và nghiệp chung thì gọi là đồng nghiệp.  
  
Trong kinh Thủ Lăng Nghiêm, Phật có lấy một ví dụ để nói về biệt nghiệp vọng kiến. Khi đó Đức Phật nói: Trước một cây đèn đang cháy, người nhặm mắt thấy chung quanh ngọn đèn có một cái vòng đỏ hoặc xanh. Còn những người mắt lành thì chỉ thấy ngọn đèn đang cháy mà không thấy vòng đỏ hay vòng xanh. Cái vòng quanh đèn chỉ có đối với người bị nhặm mắt, đó là do nghiệp riêng của người bệnh mắt mà có thấy, còn người không bị nhặm mắt thì không thấy. Cũng vậy, trong cuộc sống giữa đời này, tuy sống có mối liên hệ với nhau, nhưng mỗi người đều có mỗi cái nghiệp riêng của họ.  
  
Ví dụ: Người có nghiệp chủng đồng bóng như thầy bùa, thầy pháp thì họ cho rằng có ma quỉ. Còn người có tinh thần khoa học thực tế thì họ không tin có ma quỉ, họ chỉ tin những sự việc mà họ thấy và chứng minh cụ thể. Vậy những sự việc mà một hay vài người thấy đó là nghiệp riêng của họ, vì họ chuyên làm cùng nghề cùng nghiệp thì họ hưởng ứng với nó. Cũng sự kiện đó mà người khác không thấy là vì họ không có nghiệp đó.  
  
Kinh Phật ví dụ: Có hai vợ chồng kia, chồng thì mù, vợ thì điếc. Hai vợ chồng dắt nhau ra chợ, chồng đàn vợ hát để kiếm tiền sinh sống. Hôm đó có một đám tang lớn đi qua, người chồng nghe tiếng trống kèn bèn nói với vợ:  
  
\- Đám ma lớn quá, thổi kèn đánh trống inh ỏi.  
  
Người vợ cãi lại:  
  
\- Ông nói bậy, đâu có kèn trống, tôi chỉ thấy cờ phướn, chớ không nghe tiếng kèn trống.  
  
Người chồng không chịu cãi lại:  
  
\- Bà nói bậy, tôi chỉ nghe thấy kèn trống, chớ đâu có thấy cờ phướn.  
  
Có như thế mà hai ông bà cãi lộn nhau, chồng thì nói có kèn trống không có cờ phướn, vợ thì nói có cờ phướn mà không có kèn trống. Chồng tự cho là mình đúng, vợ cũng cho là mình không sai. Hai vợ chồng cãi nhau hoài không ai chịu thua, giận tức nổi lên liền đánh lộn nhau. Người đi đường thấy mới can gián và hỏi duyên cớ. Người chồng phân bua:  
  
\- Tôi nghe đám ma thổi kèn đánh trống, tôi nói có kèn trống bả không chịu, bả nói tôi nói bậy, bả nói chỉ có cờ phướn, không có kèn trống, nên mới cãi nhau rồi nổi giận đánh lộn.  
  
Người đi đường mới nói:  
  
\- Thưa ông bà, hai ông bà đều đúng cả, mà hai ông bà cũng đều sai. Vì đám ma này có kèn có trống như ông nghe, mà cũng có cờ phướn như bà thấy.  
  
Nếu người chồng nghe tiếng kèn trống mà nhớ mình mù không thể thấy cờ phướn, và người vợ thấy cờ phướn mà nhớ mình điếc không thể nghe tiếng kèn trống thì đâu có cãi vả và đánh lộn nhau. Tại người nào cũng chủ quan, cho cái thấy nghe của mình là chân lý nên mới xảy ra cuộc cãi vả và đánh lộn nhau. Đó là nghiệp khác nhau, không thể chấp nhận nhau.  
  
Cũng vậy, chúng ta sanh ra đời mỗi người mang theo nghiệp riêng của mình mà cùng sống chung với nhiều người khác. Mỗi người chấp giữ và làm theo nghiệp riêng của mình mà không thừa nhận nghiệp riêng của người khác nên mới có sự cãi vã, tranh chấp.  

Trong một gia đình, ông chồng thì huân tập cái nghiệp của người nam, bà vợ thì huân tập cái nghiệp của người nữ. Hai cái nghiệp nam nữ tuy có vài điểm tương đồng, nhưng cũng có nhiều điểm khác biệt. Nên có nhiều gia đình vợ chồng gây cãi đánh đập nhau hoài là vì chồng chấp lý của mình là đúng, vợ cũng chấp lý của mình là đúng, không biết dung hòa nhau để sống. Cái đúng của người chồng là do thói quen huân tập cái nghiệp của người nam. Cái đúng của người vợ là theo thói quen huân tập cái nghiệp của người nữ. Thế nên phải thông cảm nhau để đối xử cho tốt đẹp, đem lại sự an vui hòa thuận trong gia đình. Khi chúng ta biết mỗi người có nghiệp riêng thì không chủ quan, không chấp mà thông cảm hòa nhịn được cuộc sống với mọi người.  
  
Xưa có một gia đình, người vợ thì tương đối tốt, biết bổn phận, biết lo làm ăn, người chồng thì bê tha rượu chè cờ bạc. Mỗi lần ông cờ bạc thua, về nhà là khảo tiền, nếu bà không có để ứng thì ông chửi đánh thậm tệ. Người thân thuộc, láng giềng ai thấy cũng đau lòng thắc mắc tại sao bà không ly dị cho rồi, cứ để ông hành hạ khổ sở như thế? Nhưng khi hỏi bà, thì bà không thể ly dị vì bà còn thương ông.  

Có nhiều gia đình có những đứa con ngỗ nghịch bất hiếu, phá gia sản gần khánh tận. Vậy mà gia đình vẫn thương, không thể từ bỏ, vì cha mẹ có cái nghiệp riêng với con. Để thấy cái nghiệp riêng của người, mình là kẻ ngoại cuộc không có nghiệp đó thì không chấp nhận, không chịu nổi. Còn người đã có nghiệp, có nợ nần nhau, dù bị đánh đập, phá phách, đối xử tàn tệ mà người ta vẫn chấp nhận chung sống, không thể rời nhau được.  

Như vậy, nếu biết được mỗi người có cái nghiệp riêng thì chúng ta có thái độ sống hết sức dung hòa, không thắc mắc, không trách cứ những hoàn cảnh khó khăn rắc rối mà người trong cuộc không giải quyết dứt khoát được, vì nghiệp riêng của họ.  
  
Nghiệp chung tức là đồng nghiệp vọng kiến. Cũng trong kinh Thủ Lăng Nghiêm, Phật có dạy: Người có nghiệp chung mới sinh ra ở chung một nước, nói cùng một ngôn ngữ, sống cùng một tập quán... Nếu có cùng nghiệp xấu thì cùng thấy điềm bất tường như sao chổi, sao phướn... Chỉ có dân nước đó trông thấy mà dân nước khác không thấy. Cũng giống như những người nhặm mắt cùng thấy chung quanh ngọn đèn đang cháy có một cái vòng xanh hay đỏ, còn những người không nhặm mắt thì không thấy. Vậy, người cùng nghiệp thì cùng cảm nhận hiện tượng giống như nhau.  

Có nhiều người thắc mắc tại sao anh chị em cùng cha mẹ sanh ra trong một gia đình, rầy la cãi hoài. Hoặc vợ chồng chấp nhận sống chung trong một gia đình, mà kẻ ý này người ý kia, bất hòa hờn giận nhau hoài là tại sao? Nếu không có duyên nghiệp với nhau tại sao gặp nhau, sống chung với nhau để khổ? Chúng ta nên biết, khi gặp nhau là đã có nghiệp đồng phần rồi, tức là đã có cộng nghiệp nên cùng ở chung với nhau. Tuy ở chung với nhau, mà mỗi người cũng có cái nghiệp riêng nên không ai giống ai. Nếu có giống chăng chỉ giống năm sáu mươi phần trăm là tối đa, không bao giờ có hai người giống nhau từ hình dáng đến tính tình.  

Phần giống nhau thì gọi là đồng nghiệp, vì đồng nghiệp nên mới cùng nhau sanh trong một gia đình, trong một đất nước. Và vì mỗi người có cái nghiệp riêng nên có người thì giàu sang sung sướng, an vui hạnh phúc, lại có người bần cùng khốn khổ. Hoặc anh em cùng cha mẹ sinh ra, học chung một trường mà có người học giỏi, có người học dở. Đó là trong cái đồng nghiệp vẫn có cái biệt nghiệp. Mà dù là đồng nghiệp hay biệt nghiệp, Đức Phật đều gọi là vọng kiến. Vọng kiến là cái thấy hư dối không thật.  
  
Tại sao nói nghiệp là vọng kiến? Ví dụ, có người nói lời xúc não làm cho mình nổi giận. Khi nổi giận thì nói lời hung ác mắng chửi, tay thì đánh đập người ta. Khi đánh đập chửi mắng người, thì bị luật pháp trừng trị. Cái khổ của tội phạm pháp này ít nhất cũng một tháng. Và nếu mình có sức mạnh, có võ nghệ, đánh người chết tại chỗ, thì tù tội khổ sở ít nhất cũng 10, 15 năm.  

Vậy, miệng nói bậy, thân làm bậy, đó là nghiệp ác. Và nghiệp ác đó từ ý nổi sân mà ra. Ý sân chỉ nổi lên khoảng 5, 10 phút mà hậu quả không lường được. Nghiệp ác của miệng và thân có ra là do ý ác chủ động. Ý ác tức là niệm sân. Chúng ta nhìn xem tướng trạng của nó ra sao? Khi (chúng ta) nhìn nó thì nó mất tiêu, không thấy hình dáng tướng mạo nó ở đâu cả. Mà không hình dáng, không tướng mạo thì không thật. Như vậy, chính cái chủ động tạo nghiệp *(ý sân)* là không thật. Cái không thật mà chỉ vì chúng ta mê chạy theo nó để tạo nghiệp thọ khổ thì thành có thật. Nên Ngài Khuê Phong nói: *"Thế không mà thành sự"*. Bản chất của cơn giận vốn là không, bất giác theo nó tạo nghiệp nên trở thành thật. Đó là nghiệp ác.  
  
Còn nghiệp lành cũng vậy. Giả sử chúng ta đi đường gặp người bệnh tật đang nằm rên rỉ bên đường. Chúng ta khởi lòng thương đem họ vô lề đường kêu xe chở tới bệnh viện để chữa trị. Vậy, lòng thương hình dáng tướng mạo như thế nào? Có thật không? - Không. Nhưng khi theo nó thì tạo nghiệp lành. Thân, miệng, ý nói, làm lợi ích cho người.  

Cái gốc tạo nghiệp ác hay nghiệp lành bản chất nó không có thật, nhưng khi theo nó thì sẽ thành nghiệp hoặc lành hay dữ. Phật dạy nghiệp là cái không thật. Tuy không thật, nếu đã làm thì sẽ cho quả, chớ không tránh khỏi. Trốn tránh người thế gian thì được, mà nghiệp thì không thể trốn được. Vì khi tạo nghiệp thì mắt thấy, tai nghe, thân cảm thọ. Chủng tử nghiệp đã chứa vào tạng thức rồi, hội đủ duyên thì quả kết tụ.  
  
Về ý nghĩa đồng nghiệp, trong kinh có ghi: Một hôm Phật ở trong hương thất trong núi Linh Thứu, gần đó có nhiều đoàn Tỳ Kheo đi thiền hành. Đoàn thứ nhất đi theo Tôn Giả Xá Lợi Phất. Đoàn Tỳ Kheo thứ hai dẫn đầu là Tôn Giả Mục Kiền Liên. Đoàn thứ ba các Tỳ Kheo đi sau Tôn Giả Ma Ha Ca Diếp. Đoàn thứ tư gồm những Tỳ Kheo đi theo Tôn Giả A Na Luật. Đoàn thứ năm là một số Tỳ Kheo đi theo Tôn Giả Phú Lâu Na. Đoàn thứ sáu là những Tỳ Kheo đi theo sự hướng dẫn của Tôn Giả Ưu Ba Ly. Đoàn thứ bảy là những Tỳ Kheo đi theo sau Đề Bà Đạt Đa. Khi đó Phật mới nói với các vị Tỳ Kheo đang ở bên cạnh:  
  
"Những Tỳ Kheo cùng đi theo Xá Lợi Phất là những Tỳ Kheo có trí tuệ lớn. Những Tỳ Kheo cùng đi với Mục Kiền Liên là những Tỳ Kheo có đại thần thông. Những Tỳ Kheo đi theo Ma Ha Ca Diếp là những Tỳ Kheo ưa tu hạnh đầu đà... Còn những Tỳ Kheo mà đi theo Đề Bà Đạt Đa là những Tỳ Kheo có tâm ác dục."  
  
Và Phật kết luận rằng: Ai cùng đi theo người nào là đã có cái nghiệp chung với người đó. Những Tỳ Kheo đi theo Tôn Giả Xá Lợi Phất là có cái nghiệp chung với Ngài về trí huệ. Những Tỳ Kheo đi theo Tôn Giả Mục Kiền Liên là có nghiệp chung với ngài về thần thông. Cho tới các Tỳ Kheo đi theo Đề Bà Đạt Đa cùng có nghiệp chung về ác dục. Cái nghiệp chung đó có từ quá khứ, hiện tại, vị lai cứ theo nhau không rời. Đó là cộng nghiệp của những Tỳ Kheo thời xưa, được Phật dạy trong kinh.  

Còn cộng nghiệp trong thời hiện tại, chúng ta thấy rất thực tế và cụ thể. Người thích rượu chè say sưa thì cùng ăn chơi thân cận với người uống rượu. Người ưa cờ bạc thì giao du với người cờ bạc. Người chuyên cần học hành nghiên cứu thì tới lui thân cận với người nghiên cứu học hành. Người thích đi chùa tụng kinh niệm Phật thì kết bạn với người đi chùa tụng kinh niệm Phật.  

Như vậy, người này thích người kia là họ có chung nghiệp *(đồng nghiệp)* nên mới hợp nhau. Để thấy trong cuộc sống này, mọi người cùng có nghiệp chung, nên mới trở thành chồng vợ, cha con, anh em, bạn bè. Và vì ai cũng có nghiệp riêng nơi dáng mạo, tính tình, năng khiếu, trí tuệ sai khác, không ai giống ai. Vậy, nghiệp nó chi phối cả đời sống chúng ta. Nếu huân tập sâu nghiệp nào thì nghiệp đó có sức mạnh, có hấp lực thu hút chúng ta đến môi trường của nghiệp đó. Vì vậy, người Phật tử biết tu hành thì thân, khẩu, ý luôn luôn phải thiện lành mới chiêu cảm được biệt nghiệp tốt và đồng nghiệp thiện.  
  
Nếu tu còn trong vòng tương đối, thì phải biết tránh nghiệp ác, tạo nghiệp lành để tạo thân tốt, tức là được biệt nghiệp tốt và sanh trong cõi thiện, có đồng nghiệp thiện. Tiến thêm một bước nữa, nếu biết nghiệp là không thật, do ý sanh ra, mà ý cũng không thật có, nó là niệm phân biệt chợt hiện chợt mất, nên không theo là dừng nghiệp ý. Nghe nói trái tai, vừa nổi bực tức muốn đánh chửi người, liền nhìn lại xem coi cái bực tức hình tướng thế nào, phát xuất từ đâu? Tìm lại không thấy hình tướng của bực tức, mà nguồn gốc khởi bực tức cũng không còn nữa. Thấy của người, lòng tham vừa khởi muốn lén lấy, liền nhìn lại coi tướng trạng của tham lam như thế nào, phát xuất từ đâu? Khi nhìn kỹ lại thì không thấy hình dáng của tham lam, và nơi chốn phát xuất ra tham lam cũng không có nữa.  
  
Như vậy, nghiệp phát xuất từ ý, ra miệng, ra thân. Mà ý là gốc phát ra nghiệp đã không thật, thì nghiệp miệng, nghiệp thân làm gì có thật. Sở dĩ thấy nghiệp có thật là do mê.  

Những nơi khác dạy khi đối duyên xúc cảnh, nếu có khởi tham lam sân giận, thì cứ lo niệm Phật nhớ Phật, thì tham lam sân giận sẽ lắng xuống. Đó cũng là một cái thuật đối trị bệnh tham, bệnh sân. Ở đây thì chúng tôi chủ trương dùng trí nhìn lại những cái xấu như tham, sân, kiêu mạn... hình dáng tướng trạng ra sao, phát xuất từ đâu? Khi nhìn lại, nếu nó tan biến là nó không thật thì nó không có sức mạnh khiến mình nói làm theo nghiệp ác. Và cứ mỗi lần đối duyên xúc cảnh, nếu có tham sân... dấy khởi lên, nhìn lại xem tường tận thấu đáo, thấy nó không thật thì nó không chi phối mình nói làm sai quấy. Khi tâm chúng ta thanh tịnh là đã cắt đứt được dòng tạo nghiệp là vọng tưởng, là ý nghiệp, không còn luân hồi sanh tử, được giải thoát.  
