# Chánh báo và y báo {- #chanh-bao-va-y-bao}

Chúng ta là những người học Phật, tu theo Phật, chủ yếu là phải hiểu Phật dạy như thế nào để đi đúng đường, đúng hướng, không lầm lạc. Để được lợi ích, đường hướng ấy được dạy ở bài Chánh Báo và Y Báo.  
  
Chánh báo là quả báo gốc hay là quả báo chủ yếu của nghiệp nhân đã tạo. Còn y báo là quả báo nương nơi chánh báo mà có như nhà cửa, cảnh vật xung quanh... Chánh báo và y báo là chỉ cho con người và cảnh vật thuộc về con người.  

Vậy chánh báo và y báo, cái nào là gốc, cái nào là ngọn? Nếu chúng ta không hiểu sẽ bị lầm lẫn và không biết cái nào là gốc để tu, cứ mãi chạy theo cái ngọn, rồi cả đời tu không được lợi ích. Vậy quý Phật tử học xong, tự kiểm lại xem từ lâu mình tu là tu theo ngọn hay tu theo gốc.  
  
Tại sao nói chánh báo tốt là y báo tốt?  
  
\- Vì có con người tốt mới có cảnh vật tốt. Chữ tốt ở đây là chỉ cho con người có tài, có trí, có đức hạnh. Người tài trí đức hạnh ở đâu thì hoàn cảnh sẽ chuyển theo họ trở thành tốt đẹp. Có khi nào một người bất tài, vô trí, thiếu đạo đức tạo được một sự nghiệp vẻ vang không? Nếu có là nhờ phước dư ở quá khứ, chỉ trong giai đoạn ngắn rồi cũng hoại, không bền. Người tài trí đức hạnh, dù hoàn cảnh không tốt nhưng họ có thể chuyển lần lần thành tốt.  
  
Ví dụ như nhà kiến trúc, những kỹ sư có tài đức, vì một lý do nào đó họ đến ở nơi núi rừng xa vắng. Với cảnh núi rừng này, họ hợp tác kiến thiết xây dựng cuộc sống mới. Một thời gian sau, cảnh hoang vắng rừng núi đó trở thành vùng trù phú xinh tươi. Còn nếu người bất tài, vô trí, thiếu đạo đức, dù ở trong hoàn cảnh tốt rồi cũng trở thành hư xấu, vì họ thiếu khả năng xây dựng kiến tạo, mà cảnh vật thì mau hư hoại, không được sửa chữa.  
  
Một sự kiện trước mắt chúng ta là khu Thường Chiếu, trước năm 1974 là một vùng đất hoang vắng, chỉ có tre gai, tranh, mắc cỡ... không nhà cửa, cây trái. Sau này nhờ những người biết tu có chánh báo tốt biến nơi này thành một cảnh già lam nghiêm tịnh, thanh lịch. Và Viên Chiếu cũng vậy. Mọi người đều ghi nhận cảnh Thường Chiếu, Viên Chiếu thanh tịnh, đẹp đẽ.  
  
Vậy cảnh tịnh cảnh đẹp đó là do tự cảnh đẹp hay là do người mà có? Mọi cảnh đều tùy thuộc vào con người, nên con người là chủ, là chánh báo, còn cảnh vật là bạn, tùy thuộc vào con người, nên gọi là y báo.  

Đó là chánh báo y báo của người xuất gia. Bây giờ đến chánh báo y báo của người tại gia. Mỗi Phật tử ai cũng có gia đình, nhà cửa. Nếu là một Phật tử biết tu đúng theo lời Phật dạy và là người tài đức thì cảnh gia đình nhà cửa của Phật tử ấy sẽ êm ấm, trang nhã, sạch sẽ. Ngược lại, nếu là người không biết tu, bất tài, vô trí thì cảnh gia đình họ không hạnh phúc, nhà cửa họ lụp xụp tồi tàn, túng thiếu. Vì vậy nên nói: *"Nhìn qua cảnh biết được người"* tức là nhìn y báo biết được chánh báo. Chánh báo tốt thì y báo cũng tốt, chánh báo xấu thì y báo cũng xấu theo.  
  
Người đời thường nói: *"Thời thế tạo anh hùng"* tức là hoàn cảnh đưa đẩy con người trở thành anh hùng. Cũng có người nói ngược lại *"Anh hùng tạo thời thế"* tức là người hùng, người tài đức tạo nên sự nghiệp vẻ vang trong đời. Hai câu này câu nào đúng?  

Người đời hay bàn tán: Có những người trước kia họ là những kẻ tầm thường không có tài đức, nhờ gặp cơ hội tốt họ nghiễm nhiên trở thành con người xuất chúng. Như vậy là *"Thời thế tạo anh hùng"*.  
  
Lại có một số người khác bàn rằng: "Vua Quang Trung tuy là người áo vải ở chốn quê mùa, nhưng lại là người tài trí phi thường, nên từ một con người áo vải quê mùa trở thành một vị tướng giỏi, một ông vua tài trí. Như vậy không phải *"Anh hùng tạo thời thế"* là gì?".  

Kết luận, tất cả mọi người thành công trên đời đều là *"Anh hùng tạo thời thế"*. Tại sao vậy? Vì nếu thời thế đổi thay mà chúng ta là kẻ thiếu phước, bất tài, vô trí, chúng ta không cải cách gì được hoàn cảnh, chỉ ỳ ra đó, thì vẫn là kẻ tầm thường như bao nhiêu kẻ khác. Ngược lại, dù cho thời thế có biến chuyển đổi thay trăm ngàn lần đi nữa, đối với người có tài trí đức hạnh, dù trước cảnh thuận hay nghịch họ vẫn là người dũng mãnh đứng lên cải cách xã hội, làm nên việc lớn. Vì họ là người có sẵn tài trí, phước đức.  

Người đời vì không hiểu rõ chánh báo và y báo nên cho rằng nhờ thời thế tốt nên đưa đẩy con người trở thành người tài giỏi, nên nói *"Thời thế tạo anh hùng"*. Họ đâu biết bản chất của người đó có cái hay, cái giỏi đang tiềm ẩn sẵn, khi gặp thời thế liền có cơ hội phát triển bèn trở thành người tài giỏi. Để thấy rõ con người là gốc, hoàn cảnh tùy thuộc vào con người. Người đời, kẻ nhìn khía cạnh này, người nhìn khía cạnh nọ, nên nói thế không đúng lẽ thật. Thế nên ở đây, chúng tôi khẳng định: *"Người tốt thì cảnh tốt"*. Đó là trường hợp thứ nhất.  
  
Đến trường hợp thứ hai: *"Chánh báo xấu thì y báo xấu"*. Nếu là người bất tài vô đức, dù họ có dời nhà hay thay đổi hoàn cảnh hàng trăm ngàn lần đi nữa thì họ vẫn là kẻ tầm thường khốn khổ, hết thất bại này đến thất bại khác, ở đâu rồi cảnh vật cũng điêu tàn, lụi bại. Vì họ không có khả năng xây dựng kiến tạo, làm sao có được cảnh tốt đẹp được. Như vậy, cảnh không thể làm con người hay tốt, mà chính con người mới làm nên cảnh tốt, cảnh đẹp. Để thấy rằng người có chánh báo xấu mà muốn y báo tốt, việc đó không thể được. Nên nói *"Người xấu thì cảnh xấu"* hoặc chánh báo xấu thì y báo cũng tồi tệ.  
  
Ở Việt Nam có một số người có cái tật là cất nhà lựa chỗ hàm rồng để sau này làm ăn phát đạt. Chôn ông bà cha mẹ cũng lựa chỗ hàm rồng để sau con cháu phát quan. Chúng ta lựa chỗ tốt để chuyển con người thành tốt. Vậy chuyển được không? Nếu chuyển được thì gia đình con cháu các ông địa lý giàu sang phát quan hết rồi. Vì đương nhiên các ông phải lựa chỗ tốt cho các ông trước rồi mới lựa cho mình sau. Nhưng tại sao chính bản thân của các ông và con cháu của các ông không làm quan hay làm vua, mà các ông vẫn cứ là thầy địa lý?  

Lựa chỗ tốt chôn cha mẹ để con cháu làm ăn phát tài, làm quan, việc làm đó là vì cha mẹ hay vì mình? Nếu vì cha mẹ, thì khi cha mẹ chết nên chọn chỗ nào gần nhà cao ráo để tới lui thăm viếng hương khói cho thuận tiện là được rồi. Nếu chọn chỗ chôn cha mẹ để được phát quan, trong khi mình là kẻ bất tài, thiếu phước làm sao phát quan được? Đó là một sự lầm lẫn hết sức lớn lao. Do chúng ta không thấy được cái gốc, cứ chạy theo cái ngọn để rồi hao tài tốn của, không đem lại lợi ích thiết thực. Tất cả chúng ta, nếu là người thật có đức, thật có tài thì dù ở trong cảnh ngộ nào cũng biến cảnh đó dần dần trở thành tốt.  
  
Khi nhận đất Thường Chiếu này, đứng ngoài cổng nhìn vào, chúng tôi thấy phía trước đường đi thoai thoải thấp, phía trong là cái gò đất cao. Chúng tôi nghĩ: Nếu cất chùa trên gò đất cao, nhìn ra đường thì đẹp lắm. Bấy giờ chưa có tiền cất chùa, chúng tôi trồng hai hàng dương trước. Đến khi đủ duyên cất chùa thì dương đã có sẵn, tạo thành cảnh chùa nghiêm tịnh, thanh lịch, đa số người đến chùa đều ưa thích. Để thấy, đó là phước duyên của con người, nên sắp đặt công việc được thành công, nếu không có phước duyên thì tính trật thất bại. Nên nói *"Người là chủ, cảnh là bạn tùy thuộc theo người"*. Hay nói cách khác *"Chánh báo tốt thì y báo tốt"*. Hiểu như vậy, Phật tử chúng ta phải làm sao xây dựng chánh báo cho tốt đẹp, vì chánh báo chính là (tài trí, đức hạnh ở nơi) con người. Y báo là sự nghiệp, của cải, tài sản thuộc về con người.  
  
Nói chánh báo là con người, đó là lối nói đơn giản, chứ chánh báo là phần sâu kín tế nhị hơn, đó là tâm. Vì tâm chủ động tất cả. Nếu tâm nghĩ tốt thì miệng nói tốt và thân hành động tốt, tất cả cảnh sở thuộc về người mới tốt đẹp. Bởi vậy, nói đến chánh báo là nói đến tâm. Kinh Duy Ma Cật, phẩm Tịnh Quốc Độ có câu: *"Tùy kỳ tâm tịnh tức Phật độ tịnh"* nghĩa là tâm thanh tịnh thì cõi nước theo đó mà thanh tịnh. Do đó nói tâm người là gốc.  

Tôi dẫn một câu chuyện để quý vị thấy tâm người là gốc và cảnh do tâm mà chuyển. Tôn giả Mục Kiền Liên là đệ tử lớn của Phật, nổi tiếng là có thần thông bậc nhất. Sau khi chứng A La Hán, Ngài nghĩ đến mẹ là bà Thanh Đề. Bình sanh bà sống không lương thiện, tánh tình keo kiệt, tham lam. Tôn Giả sợ bà thác sanh vào đường ác, nên dùng thiên nhãn thông để xem bà sanh ở cõi nào. Tôn Giả nhìn đến cõi ngạ quỉ thấy bà đang làm quỉ đói, thân hình tiều tụy vô cùng đói khổ. Động lòng thương, Tôn Giả đi khất thực được một bát cơm, liền vận thần thông đem dâng cho mẹ. Bà vốn là kẻ đầy lòng tham lam và bỏn xẻn, khi vừa được bát cơm, một tay bà bốc cơm, một tay che lại, sợ kẻ khác thấy giật cơm của bà. Do tham lam, bỏn xẻn còn đầy dẫy trong lòng bà, nên cơm vừa đưa tới miệng thì hóa thành lửa, bà không ăn được, vẫn đói khổ. Nếu lúc đó bà phát tâm hỷ xả, thì chắc cơm không hóa thành lửa. Tôn Giả Mục Kiền Liên trông thấy cảnh khổ của mẹ, Ngài không biết làm sao cứu mẹ thoát khỏi kiếp ngạ quỉ, bèn trở về Phật bạch tự sự. Thế Tôn dạy: Một mình ông không đủ oai lực chuyển tâm niệm của mẹ ông. Vậy nhân ngày chúng tăng hội về tự tứ, ông hãy sắm sửa trai nghi để cúng dường các vị Thánh Tăng, và nhờ cầu nguyện khiến cho mẹ ông chuyển tâm tham lam, bỏn xẻn thì sẽ thoát kiếp ngạ quỉ.  
  
Nghe qua, ắt quí vị có nghi ngờ. Theo lý nhân quả thì người khi đã tạo nhân thì phải thọ quả. Bà Thanh Đề tạo nhân tham lam, bỏn xẻn nên phải chịu quả báo làm quỉ đói, tại sao chúng Tăng cầu nguyện mà bà khỏi kiếp ngạ quỉ thì trái với lý nhân quả. Như trước đã nói tâm là gốc, tâm là chánh báo. Nếu tâm chuyển thì chánh báo và y báo theo đó mà chuyển. Tâm bà Thanh Đề tham lam và bỏn xẻn đó là chánh báo xấu nên y báo cũng xấu là sống trong cõi ngạ quỉ đói khổ. Bây giờ bà được chúng Tăng thành tâm cầu nguyện chuyển tâm tham lam, bỏn xẻn của bà thành tâm từ bi, hỷ xả. Vì tâm của chư Thánh Tăng thanh tịnh đồng hướng về bà, nên có oai lực, có sức mạnh, khiến bà cảm được niệm lành, bà liền thức tỉnh chuyển tâm tham lam, bỏn xẻn thành tâm từ bi hỷ xả. Ngay đó bà được thoát kiếp ngạ quỉ, sanh lên cõi thiện lành.  

Chúng ta đừng nghĩ rằng chư Tăng cầu nguyện là thân nhân mình được giải thoát. Điều đó không đúng. Nếu chúng Tăng cầu nguyện mà thân nhân mình thức tỉnh, chuyển tâm xấu ác thành tâm thiện lành, thì mới chuyển đổi được kiếp đọa lạc mà sanh vào cõi thiện lành. Ngược lại, nếu không chuyển được tâm thì hoàn cảnh cũng không đổi thay. Vì y báo tuỳ thuộc vào chánh báo là tâm.  
  
Chủ yếu của người tu là phải chuyển tâm, khi tâm chuyển thì thân và cảnh mới chuyển theo. Nếu tâm không chuyển thì thân và cảnh không thể chuyển được. Tại sao một mình Tôn Giả Mục Kiền Liên không khiến cho bà Thanh Đề chuyển được mà phải nhờ nhiều vị Thánh Tăng khác? Điều này mới nghe qua có vẻ huyền bí, nhưng kỳ thật không có chi là huyền bí cả. Mỗi người chúng ta đều có nhân điện, mà nhân điện đó có một sức mạnh, nếu chúng ta luyện tập và biết ứng dụng vào cuộc sống thì nó có tác dụng rất cụ thể. Chẳng hạn như trị bệnh bằng cách xoa sát hay xoa bấm huyệt là truyền nhân điện làm cho người hết bệnh nơi thân. Cũng vậy, chư Thánh Tăng là những bậc tu hành viên mãn, tâm các Ngài thanh tịnh trong sáng, cùng hướng về một người cầu nguyện thì có một sức mạnh, có sự cảm ứng nơi người nhận.  

Vấn đề này trong thực tế chúng ta thấy có những sự kiện xảy ra rất cụ thể. Như trong gia đình hoặc cha hay mẹ hấp hối, khi đó người con đang ở xa, cả gia đình từ cha mẹ đến anh chị em đều trông người con ấy về để gặp mặt. Khi đó người con ở xa cảm thấy lòng xao xuyến bức rức. Tại sao? Vì tâm lực *(nhân điện)* của những người thân trong gia đình đang hướng về người con ấy nên có sức giao cảm khiến cho lòng xao xuyến bức rức. Nhưng vì tâm lực *(nhân điện)* của những người thân đó yếu nên người con ở xa chỉ cảm thấy lòng xao xuyến mà thôi. Nếu tâm mọi người thanh tịnh thì sẽ có sức giao cảm mạnh khiến cho người nhận biết rõ điều gì mà người trong gia đình muốn cho họ biết.  

Sự kiện này rất cụ thể, tuy quá tầm mắt của chúng ta nên khó tin, nhưng không phải là không có. Cho nên những nhà thôi miên họ dùng nhân điện điều khiển được những người mà họ muốn điều khiển một cách dễ dàng. Để thấy mỗi người chúng ta ai cũng có nhân điện. Nếu nhân điện mạnh của nhiều người đồng hướng về một người nào để cầu nguyện cho người đó chuyển tâm niệm sẽ được thành tựu. Nên nói cầu nguyện có kết quả là như vậy, chớ không phải chư Tăng nguyện rồi Phật hay thiên thần tới rước đi về cõi khác. Đó là lòng thành, do sức nguyện cầu khiến cho tâm xấu ác của người trở thành tâm thánh thiện. Và khi tâm thánh thiện thì nghiệp đã chuyển nên sanh về cõi thiện, đâu có trái lý nhân quả.  
  
Hiểu như thế chúng ta mới không nghi ngờ chánh báo và y báo trái với lý nhân quả. Nhưng nhớ, chánh báo mà chuyển được là phải có cơ hội, có sức mạnh đánh thức mới chuyển nổi, chứ bình thường khó mà chuyển đổi. Cũng như quý Phật tử khi chưa biết đạo không thích đi chùa, không thích làm phước... nhưng nhờ một cơ duyên nào đó, chẳng hạn như trong gia đình có xảy ra tai biến khổ đau, bạn bè rủ đi nghe pháp, nên được thức tỉnh và chuyển tâm niệm liền thay đổi cuộc sống.  
  
Quý vị đã thấy tầm mức quan trọng nhân điện của chư Tăng đánh thức tâm niệm của người nghiệp chướng nặng nề. Và quý vị phải nhớ, Phật dạy hàng Thánh Tăng đã chứng lục thông La Hán tâm thanh tịnh mới có đủ oai lực, chớ không phải hàng Tăng Sĩ lôi thôi. Chúng ta bây giờ vì không hiểu ý nghĩa, chỉ chú trọng hình thức, miễn thỉnh được các thầy đầu tròn áo vuông tụng ê a, chuông mõ rền vang là được rồi. Chớ không cần biết các vị Tăng ấy có giữ trai giới, phạm hạnh thanh tịnh không. Phần sức mạnh tinh thần thì không lưu ý. Nếu chư Tăng không giữ trai giới, phạm hạnh thanh tịnh mà cầu nguyện thì có khác gì quý Phật tử cầu nguyện.  

Vậy tốt hơn là cả gia đình, cả gia quyến hợp lại tụng kinh, thành kính cầu nguyện cho cha mẹ còn có ý nghĩa hơn. Tập trung tinh thần hướng về một người để cầu nguyện: Nếu tinh thần những người cầu nguyện trong sáng thì có ảnh hưởng tốt, nếu tinh thần của những người cầu nguyện đen tối thì làm sao chuyển đổi nghiệp chướng cho người, e còn làm nặng nề thêm là khác. Vì *"Tâm tịnh là cõi nước tịnh"*. Cho nên pháp môn Tịnh Độ dạy Phật tử niệm Phật là phải niệm cho nhất tâm rồi thì không còn một niệm dấy khởi. Mà niệm không khởi thì đâu có nghĩ xấu nghĩ bậy, tâm không tịnh là gì ? Mà tâm tịnh nhất định sanh về cõi tịnh. Ngược lại, nếu tay lần chuỗi miệng lâm râm mà tâm còn toan tính chuyện hơn chuyện thua, chuyện được chuyện mất, thì có niệm vô số câu A Di Đà Phật tâm vẫn còn nhiễm ô, Phật cũng không rước về cõi tịnh.  
  
Có một số Phật tử hỏi rằng: Người niệm Phật cầu sanh về Tịnh Độ, sau khi chết được Phật A Di Đà rước về cõi Cực Lạc. Còn người tu thiền không cầu sanh về cõi nào, sau khi chết đi về đâu, chẳng lẽ đi lang thang?  
  
Đáp: Người tu thiền có hai trường hợp:  
  
Một là đạt được thiền định. Đối với những người sạch hết vọng tưởng nên tâm thanh tịnh nhất như, quyết định là sẽ được giải thoát Niết Bàn.  
  
Hai là đối với người loạn tưởng đã giảm, tâm chưa trong sạch hoàn toàn nhưng có phần thanh tịnh, khi chết chưa vào Niết Bàn được. Tuy nhiên, tùy tâm tịnh ở mức độ 50% thì đến cõi tịnh 50%, nếu tâm tịnh được 80% thì đến cõi tịnh được 80%... Rất là vô lý, khi tâm tịnh mà không biết chỗ đến lại đi lang thang. Lang thang là kiếp ngạ quỉ, do nhân tham lam, bỏn xẻn mới chịu quả báo đói khát, lang thang. Người tu tâm thanh tịnh, lại từ bi hỷ xả thì làm gì phải lang thang?  

Ví dụ có một người đi Huế, người ấy có thân nhân ở Huế, cho nên yên lòng ra đó sẽ ở nhà thân nhân. Một người khác cũng đi Huế, người này không có thân nhân ở Huế, nhưng người ấy có mang theo tiền để chi dùng trong chuyến đi. Khi đến Huế họ mướn khách sạn, vậy ai hơn ai? Chúng ta có thể bảo người không có thân nhân ở Huế, đến Huế họ đi lang thang được không? - Không. Vì họ có hành trang để đi đường. Cũng vậy, người chỉ sợ tâm không thanh tịnh, đừng lo không có cõi tịnh để mình đến. Phải hiểu cho thật rõ chỗ này kẻo tu bị lầm lạc. Đứng bên này chỉ trích bên kia, phê phán bên nọ làm một việc hoang mang nghi ngờ cho người mới tu học, là quá lôi thôi, không lợi ích. Chúng ta hiểu rõ tâm ai thường thanh tịnh, người đó sẽ được sanh cõi tịnh. Chẳng những Phật tử tu thiền, tu Tịnh Độ, mà người không qui y làm Phật tử, nếu tâm họ tịnh cũng sanh được vào cõi tịnh. Vì chánh báo tốt ắt hẳn y báo phải tốt.  
  
Bây giờ ứng dụng lý chánh báo và y báo vào việc tu hành. Trước là bản thân của người xuất gia. Thông thường nhiều người xuất gia có quan niện tu là phải cất chùa to, đúc tượng Phật lớn, trang trí cảnh chùa cho đẹp, quên đi phần tu học cho bản thân. Nếu người xuất gia mà không tu học làm sao có tài có đức để cho người kính tin kết duyên mà làm Phật sự? Vì vậy mà phải xoay lại bản thân mình để lo tu học, một khi có đủ tài đức thì chùa to cảnh đẹp ắt sẽ có.  
  
Xưa có nhiều vị Thiền Sư ẩn tu trong những hang đá, am tranh trên núi rừng là người tu hành chân chính, tài đức vẹn toàn. Khi có người biết đến liền thỉnh về kinh đô để ở những ngôi chùa lớn để hoằng dương chánh pháp. Chúng ta ham ở chùa to, cảnh đẹp mà bất tài, thiếu đức lại tu hành lôi thôi, sớm muộn gì cũng bị người mời ra khỏi chùa, để thỉnh người xứng đáng về trụ trì. Như vậy mới thấy chánh báo không tốt mà đòi y báo tốt thì không thể được. Chúng ta tu phải làm sao cho tài trí đức hạnh, chớ không lo có chùa ở.  
  
Kế là việc giáo hóa đệ tử. Người tu phải lo cho đệ tử như thế nào? Nếu người thông lý chánh báo y báo, trước phải dạy đệ tử tu học cho có đức, có tài. Đức do tu mà có, tài do học mà có. Tài đức vẹn toàn rồi thì lo gì mai sau không xiển dương Phật pháp. Vì đã có chánh báo tốt, chắc chắn y báo sẽ theo đó mà tốt. Còn lo cất chùa cho đẹp cho kiên cố, để lại hằng trăm năm cho đệ tử ở, nếu là đệ tử bất tài vô đức, tu hành lôi thôi, thì chẳng làm gì lợi ích cho Phật pháp. Lại có thể, nó cởi áo tu, hoàn tục, bỏ chùa hoang, không người hương khói. Lo cho đệ tử như vậy không bảo đảm. Vậy lo chùa để lại cho đệ tử, không bằng lo cho đệ tử có đức có tài, tu hành chân chánh, hợp với chánh pháp.  
  
Chúng tôi thường nói rằng: *"Sau này chúng tôi tịch rồi, chỉ để lại một số người biết tu, biết đạo chớ không để lại chùa tốt, chùa sang"*. Ngôi chánh điện Thường Chiếu tôi cất chỉ có hai mươi ngày là xong. Các nơi nghe tôi cất chùa chỉ có hai mươi ngày họ cười nói *"Chùa dã chiến"*. Mà thật, *"Chùa dã chiến"*. Vì nó không ra gì hết. Trên Chân Không có bao nhiêu vật liệu, đem xuống Thường Chiếu ráp lại vừa đủ, không thêm gì hơn. Chúng tôi chỉ cần có chỗ cho Tăng Ni tu, Phật tử đến học đạo là được rồi. Sau khi tôi tịch, nếu ai có tài trí phước đức hơn tôi họ muốn sửa chữa cho đẹp hơn là tùy họ. Chúng tôi chỉ nghĩ làm sao đào tạo một số Tăng Ni có học, có tu, có tài, có đức để lại cho đạo là đủ rồi. Còn chùa cảnh thì chúng tôi không đặt nặng. Đó là phương hướng giáo hóa đệ tử.  
  
Kế đến là làm Phật sự. Phật sự thì có liên hệ đến Phật tử tại gia nhiều. Phật tử khi làm Phật sự thì nhắm vào y báo hay chánh báo? Đa số Phật tử nghe nói xây chùa, đúc tượng Phật thì thích lắm, còn nghe nói nuôi Tăng Ni tu học thì không thích. Tại sao vậy? Vì mình làm cực khổ mới có tiền của, đem đến nuôi người nhàn rỗi hơn mình là điều không được vui, nên không thích. Hơn thế nữa, đem bao nhiêu của đến Tăng Ni ăn cũng hết, không còn để lại cái gì thấy là của mình đã cúng. Còn cất chùa, tạo tượng, đúc chuông để lại đời đời, cái mà mình đã cúng vẫn còn đó, thì thích hơn. Vì nó có hình thức dễ thấy.  

Hình thức đó thuộc về y báo. Nếu chùa tốt, Phật to, chuông thanh mà không có một vị Tăng tu hành chân chánh gìn giữ xiển dương chánh pháp, thì cất chùa có lợi ích gì? Vậy, Phật tử hiểu đạo rồi nên ứng dụng lý chánh báo và y báo để làm Phật sự mới hợp đạo. Chúng ta Phải làm sao cho ngày mai có những Tăng Ni tài đức để duy trì pháp Phật được lưu truyền, sau đó mới gìn giữ chùa chiền là thờ kính Phật. Vậy việc chính của chúng ta là phải phát triển chánh báo cho tốt rồi y báo sẽ theo đó sẽ tốt. Nếu chỉ một bề lo y báo mà không lo chánh báo thì sẽ bị suy thoái về sau. Đâu quý vị kiểm lại xem Phật sự quý vị đã làm là nhắm vào gốc hay vào ngọn? Đa số là nhắm vào hình thức.  
  
Ví dụ như các thầy dự định xây mái cổng chùa, có một Phật tử giàu có đến xin hỷ cúng một mình, để cổng chùa ấy mang tên của mình cúng. Tên người lẫn cổng chùa vẫn còn lưu lại đến năm ba chục năm. Còn nếu cúng một hai triệu để nuôi 100 vị Tăng ăn tu, chỉ vài tháng là hết, tên người cũng không còn, nên không vui không thích. Cúng cổng chùa mỗi lần đi ngang qua nghĩ cổng chùa mình cúng còn đây. Quý vị nên nhớ rằng chư Tăng ăn của tín thí tuy hết, nhưng họ lo tu học cho tâm trí được sáng suốt, đức hạnh được tăng trưởng, thanh tịnh. Mai sau, họ là người hoằng dương chánh pháp, làm cho Phật pháp trường tồn lợi ích chúng sanh. Nếu không có những người đó thì lấy ai duy trì Phật pháp giáo hóa chúng sanh?  
  
Bây giờ đến phần ứng dụng lý chánh báo y báo trong cuộc sống hằng ngày của Phật tử. Trước hết là ngay bản thân mình việc trước mắt là phải trau dồi tài đức, chớ đừng nghĩ mai kia mình có địa vị làm ông này bà nọ, sẽ giàu sang phú quí. Nếu mình có đủ tài đức thì mọi việc tốt nó sẽ đến với mình. Giả sử có một đứa học sinh đi học, ngày ngày cứ mơ ước mai sau sẽ làm bác sĩ hay bác học, mà hiện tại vào lớp không chịu học hành, cứ thả hồn mơ ước viễn vông. Cuối năm thì thi rớt, vậy mai sau có làm bác học, bác sĩ được không? Chắc chắn là không. Ngược lại có một học sinh khác không mơ ước mai sau làm gì cả, mỗi ngày vô lớp chăm chỉ, siêng năng học hành, nên học giỏi nhất nhì trong lớp. Và cứ như thế, hết niên khóa này tới niên khóa khác, và cuối cùng là được tuyển vào khoa học hay y học để rồi ra làm bác sĩ, bác học. Mơ ước những điều cho ngày mai là việc làm không thực tế. Mà thực tế là hiện tại phải làm sao trau dồi cho có tài đức, thì mọi sự tốt đẹp dù không muốn cũng đến. Vì chánh báo tốt thì y báo tốt sẽ đến.  
  
Sau là việc dạy dỗ con cháu. Có nhiều Phật tử quan niệm là phải làm sao có nhiều tiền của để lại cho con cháu. Nếu có nhiều tiền của mà con cháu bất tài vô đức, lêu lổng ăn chơi thì càng thêm hư hỏng. Cùa cải khó bề bảo quản, sớm muộn gì rồi cũng tiêu tán. Thế nên thương và lo cho con cháu là phải lo cho nó học để có tài, phải giáo dục cho nó có đức. Nếu có tài có đức thì mai kia nó sẽ nên người, làm được việc mà chúng ta mong muốn. Chớ dành dụm của cải để lại cho con cháu, mà nó bất tài thiếu đức thì không gìn giữ được. Vì của cải thì có thể bị con cái phá, trộm cắp cướp đoạt mất đi. Chớ tài đức thì không ai cướp giật được.  

Lại có nhiều người nhìn phiếm diện, chỉ lo cho con học giỏi thôi, không nghĩ gì đến đức hạnh của nó. Đó là một khuyết điểm lớn cùa người làm cha mẹ. Trên đời nhiều người làm tội ác tày trời đâu phải là những người dốt, bất tài. Chẳng hạn như những thủ lãnh cúa những đảng cướp lừng danh thế giới đâu phải là những kẻ ngu bất tài. Người càng tài giỏi mà không đạo đức là càng họa to cho xã hội. Cho nên có tài thì phải cần có đức. Tài thì nhà trường đào tạo, đức không phải tự nó mà có mà do cha mẹ kết hợp nhà trường hướng dẫn giáo dục. Được như thế mới có thể gìn giữ sự nghiệp của mình và làm lợi ích cho nhân quần xã hội.  
  
Như chúng ta đã biết gốc của chánh báo là tâm. Gần đây, quý Phật tử nghe nói pháp tu Tịnh Độ quá đơn giản là gần lâm chung niệm Phật từ bảy đến mười câu cũng được Phật rước về cõi Cực Lạc. Điều này phải nghiệm lại cho kỹ. Kinh A Di Đà, Phật dạy: Niệm Phật cho đến nhất tâm bất loạn ít nhất là một ngày, hoặc hai ngày... cho đến bảy ngày. Nhất tâm bất loạn tức là định, mà định là tâm thanh tịnh, mà tâm thanh tịnh thì sẽ sanh về cõi Phật tịnh. Phật dạy thật rõ ràng. Vậy mà tay chúng ta lần chuỗi miệng niệm Phật tâm thì nghĩ vô số chuyện. Như vậy là tâm quá loạn thì làm sao về cõi tịnh được? Nên Phật vì lòng từ bi có rước về cõi Phật, chúng ta cũng không ở được. Vì tâm chúng ta quá ô nhiễm, tham sân si còn dẫy đầy làm sao tương ứng được với cõi tịnh mà ở, rốt cuộc rồi cũng phải trở lại cõi Ta Bà uế trược này. Vì chánh báo nào y báo nấy.  

Chuyện thế gian gần nhất là nhiều người đi nước ngoài, trong số đó cũng có một số người chịu sống ở nước ngoài, nhưng cũng có một số người muốn trở lại Việt Nam. Trong khi họ đi họ nghĩ rằng ra nước ngoài sẽ sung sướng hơn. Nhưng khi đến nước ngoài vì văn hóa kém, ngôn ngữ của người không nói được, phong tục tập quán của mình không thể kết hợp được... Nên cảm thấy lạc loài, muốn trở về Việt Nam. Người niệm Phật mà tâm không thanh tịnh, còn loạn động bởi tham sân mà muốn về Cực Lạc cũng na ná như thế ấy.  
  
Người tu thiền cũng vậy, chúng ta đừng mong chứng Niết Bàn, mà phải tu làm sao cho hết vọng tưởng phiền não. Vọng tưởng phiền não hết thì Niết Bàn hiện tiền. Trái lại, tu mà mong mau chứng Niết Bàn, sẽ bị ma quấy nhiễu rồi dẫn vào đường tà. Niết Bàn là gì? Niết Bàn là tâm thanh tịnh. Nếu vọng tưởng phiền não hết thì tâm thanh tịnh đó là Niết Bàn, không cần mong cầu tìm kiếm. Đó là một lẽ thật, đừng mong ước Niết Bàn trong khi tâm mình còn dẫy đầy vọng tưởng phiền não, thì không bao giờ được Niết Bàn như ý muốn.  
  
Vậy, chủ yếu của sự tu hành là ở tâm. Tâm được thanh tịnh là do tu thiền định, gạn lọc tham sân si phiền não hết sạch, rồi trải lòng thương giúp đỡ người, làm cho mọi người được an vui lợi ích. Mình vui, người vui thì đâu có chán nản mong tâm đi đây, đi kia! Vì tâm mình ích kỷ, đố kỵ ganh ghét thấy ai cũng xấu xa tồi tệ, nên chán, tự cô lập mình thành một cái ốc đảo nên cô đơn lạc loài. Nếu ở chỗ này với tâm ích kỷ phiền não thấy mình lạc loài, tới chỗ khác cũng sẽ bị lạc loài. Tu là hiện tại phải chuyển tâm, tâm chuyển thì cảnh chuyển. Chớ trách cảnh, trách người xấu, mà hãy tự trách mình còn nhiều thói hư tật xấu, nên y báo xấu nó theo mình. Vì vậy, tự mình phải lo tu sửa cho tâm được tốt, cho tâm được thanh tịnh.  
  
Chúng ta hiểu rõ lý chánh báo y báo rồi, thì phải ứng dụng trong đời tu, trong khi làm Phật sự, trong cuộc sống gia đình, giáo dục con cái cho đúng, thì sẽ được lợi ích rất lớn, không riêng cho bản thân mình mà còn lợi ích cho tất cả mọi người chung quanh.  
