# Bồ Tát sợ nhân, chúng sanh sợ quả {- #bo-tat-so-nhan-chung-sanh-so-qua}

Nhiều Phật tử đi chùa quy y đã lâu, biết tụng kinh niệm Phật, thế mà đối với lý nhân quả chưa đủ lòng tin. Nếu chưa đủ lòng tin nhân quả thì giáo lý Phật coi như chưa hiểu gì cả, vì lý nhân quả là nền tảng của Phật pháp. Tin lý nhân quả là điều thiết yếu nhưng không phải tin suông, tin mù quáng mà là một sự kiện thực tế, cụ thể ngay trong cuộc sống, rất sáng tỏ, không mơ hồ huyền hoặc.  
  
Thế nào là *"Bồ Tát sợ nhân, chúng sanh sợ quả"*?  
  
Bồ Tát nguyên chữ Phạn là Bodhisattva, dịch âm là Bồ Đề Tát Đỏa, dịch nghĩa là hữu tình giác. Tức là một chúng sanh đã giác ngộ và đang giúp cho những chúng sanh khác cũng được giác ngộ như mình, thì gọi là Bồ Tát. Nhờ đã giác ngộ thấu suốt được lý nhân quả trong ba đời, nên chỉ sợ nhân mà không sợ quả. Chúng sanh là loại hữu tình có sinh có tử còn vô minh nên đi mãi trong vòng luân hồi. Vì chưa giác ngộ, còn mê mờ không thông lý nhân quả nên chỉ sợ quả mà không sợ nhân. Vậy kiểm lại trong chúng ta, ai là người biết sợ nhân xấu đó là người giác, là Bồ Tát, ai sợ quả xấu là kẻ mê, là chúng sanh.  

Bồ Tát hay chúng sanh là tự chúng ta có thấy biết đúng sự thật hay không, chớ không phải Bồ Tát cỡi hạc hay cỡi sư tử đi trên hư không để cho người ngưỡng vọng lễ bái. Nếu giác, thấy đúng lẽ thật, nhận biết một cách chính xác nhân nào đưa đến quả khổ, nhân nào đưa đến quả an lạc. Do biết rõ, nên thấy nhân nào đưa đến quả khổ quyết định không làm, vì tạo nhân rồi thì không tránh được quả, đó là Bồ Tát sợ nhân. Ngược lại, cái nhân đưa đến quả khổ nếu chúng ta không biết để tránh, mà chỉ thấy quả khổ đến lo sợ tránh né, đó là chúng sanh sợ quả.  

Ví dụ người có tật nóng giận, mỗi khi có người trong nhà hay hàng xóm nói hoặc làm điều gì trái ý liền la lối đánh đập. Nếu chửi bới hay đánh đập vợ con trong nhà bị thương tích thì tốn tiền thuốc thang chữa trị, bị xóm giềng cười chê là đồ bất nghĩa bất nhân, khiến tâm ray rứt hối hận.  
  
Nếu đánh đập người ngoài xã hội có thương tích thì bị người đánh lại hay bị bắt bớ, giam cầm. Khi đánh chửi thì không sợ, đến khi thấy vợ con đau bệnh hoặc bị người đánh lại, hay bị tù tội thì lo sợ. Đó là người mê hay tỉnh? Vì mê không biết nhân xấu ác sẽ đưa đến quả khổ, nên cứ làm rồi thọ quả khổ chừng đó mới sợ.  
  
Người có lòng tham, thấy của người dễ lấy, liền lấy đem về làm của mình. Khi lén lấy của người thì không sợ mà chỉ thích thú là mình được của. Để khi chủ nhà hay mất của, báo nhà chức trách truy tìm lùng bắt kẻ trộm thì lo sợ. Đó là người mê, vì mê nên không biết tạo nhân xấu phải chịu quả khổ, cứ làm để rồi quả khổ đến thì hoảng kinh lo sợ.  
  
Có nhiều thiếu niên 14, 15 tuổi thấy người lớn hút thuốc nhả khói phì phà có vẻ oai vệ, thư nhàn nên tập hút, hút một thời gian thì ghiền. Khi ghiền, nếu có thuốc hút thì tạm ổn, hôm nào không tiền mua thuốc thì ngáp dài chảy nước dãi thèm thuồng, chịu không nổi, tới người này, người kia năn nỉ mượn tiền mua thuốc hút, thật là khổ sở. Đó là cái quả chặng thứ nhất. Đến quả chặng thứ hai là hút tới lới tới già thì bị nám phổi, ung thư phổi, bệnh trầm kha, khốn khổ vô cùng. Lúc hút thuốc hồn lâng lâng quyện theo khói theo mây thì không sợ. Đến khi cơn ghiền hành hạ không tiền mua thuốc, bệnh hoạn bứt ngặt không tiền uống thuốc, không thuốc để điều trị, chừng khổ đến mới sợ.  
  
Lại có những chú bé mười lăm, mười bảy tuổi thấy cha chú uống rượu bàn tán việc làng việc nước, việc cổ kim thời sự ra vẻ người hiểu biết sành đời, nên thích thú tập uống. Khi mới uống thì cảm thấy cay nóng, tập một thới gian trở thành dễ chịu và đi tới ghiền. Khi ghiền rồi thì mỗi ngày phải có rượu mới yên, nếu không rượu thì uạ ọc, bực bội, khó chịu. Đó là cái quả thứ nhất không rượu uống. Nếu gặp tiệc tùng anh em đông đảo, người chén thù người chén tạc, kết quả là say túy lúy, đi ngã bờ ngã bụi làm trò cười cho thiên hạ. Khi về đến nhà thì chửi đánh vợ con, ói mửa đầy đất hôi hám nhơ bẩn nhà cửa, khiến cho cha mẹ vợ con buồn chán. Đó là cái quả thứ hai, làm cho gia đình mất hạnh phúc. Đến cái quả thứ ba là chai gan, loét dạ dày... đau bệnh trầm kha vô cùng khốn khổ. Từ cái nhân nhỏ đưa tới cái quả thật to, mà người ta không thấy nên mới tạo, để rồi thọ quả vô cùng khốn khổ, hối hận thì không kịp.  

Vậy, người tập tành những thói hư tật xấu đó là giác ngộ hay mê? Bởi mê nên mới khổ. Nếu giác như Bồ Tát biết rõ hút thuốc, uống rượu là cái nhân đưa tới nghiện ngập, bệnh hoạn nghèo khổ, gia đình mất hạnh phúc. Biết như vậy, nhất định không uống, không hút, dù người có cố tình mời mọc, dứt khoát không dùng. Đó là người sống có tỉnh giác nên không khổ.  

Nếu sống mà không biết nhân nào đưa tới quả khổ, nhân nào đưa tới quả vui, mặc tình tạo tác để rồi quả đến thì kêu trời trách đất. Đó là người mê muội không biết tránh nhân, chỉ biết sợ quả nên bị khổ đau. Vậy chúng ta hiện có mặt ở đây tự xét lại coi mình là người giác hay kẻ mê? Ai cũng muốn mình là người giác, không bị khổ đau bứt ngặt thì nên tập hạnh của Bồ Tát là biết tránh nhân xấu, chớ không sợ quả xấu.  
  
Ở thế gian có nhiều trường hợp mới thoạt nhìn thấy dường như rất tốt, nhưng nhìn kỹ thì chẳng tốt chút nào. Chẳng hạn, người biết hút thuốc gặp người chưa biết hút thì mời ép cho hút, đến khi ghiền thuốc rồi, không tiền mua, xin thì không cho. Hoặc người chưa biết uống rượu được người biết uống rượu mời mọc ép uống, đến khi ghiền rồi thì ít khi được mời uống. Vậy, những người bạn thuốc, bạn rượu có thật thương, thật tốt với chúng ta không? Bạn thuốc, bạn rượu không phải là người để chúng ta kết giao thân thiện.  
  
Lại có trường hợp Phật tử thường đi chùa tụng kinh lạy Phật. Một hôm có người nói: *"Chị năm nay bị sao Kế Đô chiếu mạng, coi chừng bị tai nạn"*. Phật tử này không dám đi đâu, ngay cả đi chùa cũng không đi, ở nhà lo lắng buồn rầu... Phật tử đi chùa với tâm trạng như vậy, có hiểu lý nhân quả không? Sao Kế Đô đó do ai đặt ra. Nhà thiên văn địa lý nào đó đặt ra mỗi tinh tú có một cái tên, trong đó có một tinh tú mang tên Kế Đô và mỗi tinh tú vận hành theo luật thiên nhiên của vũ trụ, đâu có chủ yếu chiếu vào người nào để cho người đó thọ nạn?  

Theo lý nhân quả của Phật giáo thì do người chủ động tạo tác nhân *(nguyên nhân tạo nên sự vật, khi sự vật thành hình gọi là kết quả)* và quả cũng do người tạo tác nhận chớ không ai khác. Phật trời thánh thần không định đặt cho con người khổ hay vui, mà do con người làm chủ. Nếu tạo nhân xấu là thọ quả xấu, nếu tạo nhân tốt thì thọ quả tốt. Vậy sợ là sợ cái gì?  

Giả sử có một Phật tử đúng vào năm sao hạn xấu mà tâm lúc nào cũng nghĩ tốt, nói năng thì vui vẻ, nhã nhặn, đối với mọi người thì luôn luôn tử tế, hài hòa, thì Phật tử ấy thường được người thương hay ghét? - Thương.  

Ngược lại, nếu có một Phật tử hay đi chùa được tuổi tốt, sao hạn tốt mà tâm thường nghĩ quấy, nói năng thô lỗ cộc cằn, đối xử với mọi người thì hơn thua lấn lướt. Vậy Phật tử đó được thương hay bị ghét? - Ghét.  

Vậy, do tâm niệm xấu xa, ngôn ngữ cộc cằn thô lỗ, hành động bất hảo làm cho người ta ghét hay sao hạn làm người ghét? Và tâm niệm tốt đẹp, ngôn ngữ nhã nhặn, việc làm lương thiện khiến cho người thương hay sao hạn khiến cho người thương? Nếu người thương thì được người hoan hỉ giúp đỡ, đó là phước. Nếu có người ghét thì bị hại đó là tội.  

Rõ ràng tội phước là do ý nghĩ, lời nói, hành động mà ra. Ý nghĩ, lời nói, hành động tốt là gieo nhân lành. Đã gieo nhân lành thì quả sẽ an vui tốt đẹp. Ý nghĩ, lời nói, hành động xấu là gieo nhân ác thì gặt quả xấu khổ đau. Khổ hay sướng là do nhân tốt hay xấu chớ đâu do tuổi xấu sao hạn xấu?  
  
Đa số người Việt Nam đều ngại ngùng ngày mùng năm, mười bốn, hai mươi ba, đi đường thì không dám đi, làm việc thì không dám khởi công vào những ngày này, vì đó là những ngày xấu. Với những ngày xấu này, nếu quý Phật tử để dành tiền mua sắm thực phẩm, vật dụng cần thiết để đem đi giúp đỡ người tàn tật, bệnh hoạn hay già yếu thì ngày đó là ngày tốt hay ngày xấu? - Tốt. Trong những ngày mà đi giúp đỡ xoa dịu cho người bớt cơn nghèo túng đói khổ, không phải ngày tốt là gì? Còn những ngày khác được coi là tốt mà ra đường gặp ai cũng cãi, cũng gây rồi đi tới đánh đập, kiện cáo. Vậy ngày đó là ngày tốt hay xấu? - Xấu. Tại ngày đó xấu hay tại chửi lộn, đánh lộn thành xấu? Tại mình không biết chế ngự thân, miệng, ý mới có chuyện đánh chửi xảy ra nên xấu.  

Như vậy, ngày được mọi người cho là tốt mà gieo nhân xấu thì ngày đó cũng trở thành xấu, mà biết gieo nhân tốt thì ngày đó cũng trở thành tốt. Lỗi tại ngày giờ hay lỗi tại hành động con người? Nếu lời nói, hành động con người gây tai họa hay được an vui, thì rõ ràng con người gieo nhân và cũng chính con người chịu quả, đâu phải ngày giờ sao hạn định tốt xấu cho con người. Đã là Phật tử, có còn sợ và tin ngày giờ, sao hạn tốt xấu nữa không? Nếu còn thì lòng tin nhân quả chưa có.  

Luật nhân quả là một lẽ thực cụ thể. Vì Phật tử không hiểu, chưa tin nên nói mơ màng, tưởng tượng ra lý này lẽ nọ để mà tin mà làm. Thế nên có nhiều Phật tử đã quy y mà vẫn tin những cái quàng xiên, mơ hồ không đúng lẽ thật.  
  
Ví dụ, trong gia đình hai vợ chồng có những quan điểm bất đồng nên gây cãi nhau, lần đầu không giải quyết ổn thỏa, ít hôm sau lại cãi nữa, và cứ cãi hoài đến năm bảy lần. Rồi họ thắc mắc tại sao trong nhà cứ xào xáo hoài, họ cho rằng do cái cửa, cái bếp đặt không đúng hướng, nên đến chùa nhờ thầy giở lịch ra coi, rồi xây lại cái bếp, sửa lại cái cửa. Nhưng, xây bếp sửa cửa xong họ lại cãi nữa.  

Hai người bất đồng ý kiến mà không chịu hóa giải cho đồng, cho có một hướng chung để xây dựng cuộc sống chung cho có hạnh phúc mà lo sửa bếp sửa cửa. Chỉ làm chuyện bên lề không đúng vào đâu. Chẳng hạn có cuộc cãi vã đó là do ông chồng đang có chuyện tình cảm riêng tư, nên người vợ buồn phiền sanh ra rầy rà. Muốn cho gia đình được êm ấm, thì người chồng phải tu chỉnh thói hư tật xấu, để trở thành người chồng tốt, người chồng có đủ tư chất. Còn cái bếp cái cửa vô tri có dính dáng gì với chuyện cãi vã của vợ chồng trong gia đình? Thế mà người ta vì không hiểu nên không thấy cái nhân gây ra cái dở cái xấu, để rồi trốn tránh trách nhiệm và đổ thừa cho ngoại cảnh.  

Quý vị có tự thấy mình mỗi khi làm điều gì hư dở là nêu lý do này lý do nọ, chứ không dám nhận cái hư dở là tại mình sơ thất và can đảm chịu trách nhiệm. Đó là do tâm hồn yếu đuối, không gan dạ nhìn nhận sự thật.  
  
Nếu người Phật tử hiểu được lý nhân quả, biết được mọi sự vật xảy ra giữa mình với người đều do cái nhân từ trước, mà nhân đó chính mình tạo chớ không phải ngẫu nhiên mà có. Chẳng hạn đi đường gặp người quen vừa thấy mặt mình là họ xoay mặt đi chỗ khác, mình liền bực cho rằng họ khinh mình, bèn nói xa nói gần một hồi sanh ra gây chửi. Chửi rồi, về nhà nói rằng tôi không chọc ghẹo mà nó kênh với tôi nên tôi phải cho nó một bài học. Người nói như vậy là vô lý, vì trong sự tương giao, mình cũng như người chưa từng nói hay làm điều gì mất lòng nhau, vẫn đối xử với nhau tốt đẹp, thì có khi nào gặp nhau là khó chịu xoay mặt làm lơ? Không ai mà bất thường đến thế! Chắc chắn là mình hoặc vô tình hay cố ý đã làm cho họ xúc não rồi, nên gặp mình là họ tránh né. Đó là do mình đã gây nhân không tốt với họ rồi, chớ đâu phải vô cớ.  

Quý vị xét kỹ lại xem trong gia đình, ngoài xã hội, từ vợ chồng con cái cho đến quyến thuộc anh em bằng hữu, nếu có chuyện không ổn xảy ra, đều do nguyên nhân không tốt, hoặc người này hay người kia tạo ra mà người trong cuộc không có gan nhận trách nhiệm tự nơi mình mà đổ thừa lý này lẽ nọ. Vì thế mới có thầy bói khai thác cái nhược điểm đó để ăn tiền. Nếu Phật tử mà tin sâu lý nhân quả thì không tốn tiền coi bói.  

Ngày xưa tôi có quen một ông thầy bói, ông nói cho tôi nghe cái thuật coi tướng số của ông mà tôi cười quá chừng. Ông nói coi tay đâu cần coi, chỉ nhìn dáng người là đoán đúng tâm lý. Chẳng hạn vợ ông cả, ông chủ đến coi mà thấy người héo hon xanh xao, là biết bà đang bệnh gì rồi. Ông liền nói: Bà rất hiền lành, rất phúc hậu, trong nhà bà có người xen vô làm cho gia đình mất hạnh phúc, nên bà buồn rầu sinh bệnh hoạn... Bà khen ông coi rất hay nên trả tiền rất hậu.  

Còn nếu thanh niên nhờ xem vận mạng đen đỏ trong kỳ thi tới, thì ông nói: Không sao, cháu thế nào cũng đậu, nhớ ráng học, học giỏi thì sẽ thi đậu. Tới chừng thi, nếu đậu thì ông được khen và được thưởng, nếu rớt thì ông nói tại cháu không chịu ham học...  

Ông nói, bói là đánh vào tâm lý, đánh vào sở thích, nói cho người ta vừa lòng thì dù đúng hay không cũng thù lao tiền trọng hậu. Để thấy người coi bói là họ ve vuốt theo tình cảm, chúng ta thích cái gì thì họ cứ vuốt ngọt cái nấy để chúng ta vừa lòng, đã hài lòng thì dù nói dở cũng thành hay, nói trật cũng thành trúng. Đó là cái thuật mà người chuyên nghiệp họ kể lại cho chúng tôi nghe. Điều cần thiết của họ là khéo mồm khéo miệng. Nhờ khéo lời, nên người coi bói tốn tiền mà không lẩn tiếc, cứ đi coi hoài.  
  
Người băn khoăn, lo lắng hậu vận của mình là người không tin nhân quả. Nếu tin nhân quả thì có gì băn khoăn lo lắng? Muốn mai kia được sung sướng thì ngày nay cứ lo làm lợi ích cho mọi người. Muốn mai kia thi đậu vẻ vang thì ngày nay phải chăm học, học giỏi. Muốn cho mọi người ai thấy mình cũng mừng rỡ thì cứ đối đãi tử tế với mọi người. Mình đã tạo nhân thì quả sẽ đến, chớ không thể bỗng dưng mà có.  
  
Như vậy, quý Phật tử có nên đoán vận mệnh nữa không? Giả sử mỗi năm cần đoán hậu vận khoảng năm ba chục lần, thay vì làm việc đó, quý vị nên sắm thực phẩm, vật dụng, thuốc men cho cô nhi, người già, người bệnh, vì họ đang cần sự giúp đỡ của chúng ta.  
  
Châm ngôn Việt Nam có câu:  

> Tay cầm tiền quý bo bo,  
> Đem cho thầy bói mang lo cho mình  
  
Làm ra tiền thì phải lao động tay chân hay trí óc cực nhọc nên quý nó lắm, nhưng đem tiền đến thầy bói coi vận mạng. Nếu họ nói năm này là năm tuổi, nhằm sao la hầu chiếu mạng, hậu vận không tốt... Coi xong về nhà lo rầu, không biết tai nạn gì sẽ đến với mình, rồi bỏ ăn mất ngủ. Đi coi bói chỉ thêm buồn, thêm lo thôi, có lợi gì?  

Người tin nhân quả cứ tạo nhân lành thì quả tốt sẽ đến, còn tạo nhân ác thì dù cho có ai khen tốt, khen hay, thì quả xấu vẫn cứ đến. Giả sử, đối với một người nào đó mà mình ghét họ, khinh họ, nói xấu họ, chắc chắn là họ không quý mến mình. Ngược lại, đối với họ, nếu mình cảm thông, chân tình giúp đỡ, dù không muốn họ quý mến mình, họ vẫn cứ mến. Nhân quả theo nhau không rời, rõ ràng mà nhiều người không tin, cứ tin những chuyện bâng quơ vô căn cứ.  

Như vậy, người Phật tử hiểu rõ lý nhân quả thì tránh nhân hay sợ quả? Nếu biết tránh nhân xấu, tạo nhân tốt thì quả xấu làm gì có? Người mà biết tránh nhân xấu, tạo nhân tốt là người tỉnh hay người mê? Đó là người tỉnh, người giác, là Bồ Tát con. Bồ Tát thì sáng suốt, biết tránh nhân xấu thì quả khổ không đến nên được an lạc. Chúng sanh vì si mê, cứ tạo nhân xấu thì quả xấu cứ đến nên đau khổ.  
  
Người tránh nhân xấu thì không băn khoăn về chuyện thương, chuyện ghét, không băn khoăn về hậu vận rủi may, cứ trải lòng thương đến mọi người và làm lợi ích cho mọi người, lòng không lẩn tiếc hay toan tính. Chúng ta thường có những bất công mà không tự thấy, không đem nguồn vui đến cho mọi người mà cứ mong mình luôn được vui sướng, điều này khó có thể xảy ra.  
  
Ví dụ, muốn ráp một chiếc xe đạp hoàn hảo vừa chắc chắn, vừa đẹp, phải lựa mua những bộ phận cho thật tốt. Cần có đủ năm chục bộ phận mới ráp được chiếc xe vừa bền, vừa đẹp. Mà chúng ta chỉ có hai chục bộ phận, hoặc mười bộ phận là đồ tốt, những bộ phận còn lại là đồ xấu, khi ráp xong chiếc xe, chiếc xe có được vừa ý không? - Không. Để thấy, muốn được chiếc xe hoàn hảo thì phải chọn các bộ phận của chiếc xe cùng hoàn hảo.  
  
Cũng vậy, con người ai cũng muốn đời mình hoàn toàn vui, không muốn chút khổ xen lấn. Vậy mà khi tạo thì không chọn thuần nhân lành mà cứ để xen lấn những điều xấu, thì làm sao được quả vui hoàn toàn? Chẳng hạn, như các ông muốn thân thể được khỏe mạnh, tinh thần minh mẫn, mà lại hút thuốc, uống rượu gây cái nhân đau bệnh, thì làm sao được khỏe mạnh, sáng suốt. Muốn cho thân khỏe, tâm sáng thì phải sống có điều độ, có thì giờ nghỉ ngơi tịnh dưỡng thân tâm.  

Còn các bà, các cô ai cũng muốn tươi trẻ, vậy mà cứ buồn giận, nhăn nhó, quạu quọ hoài, thì làm sao tươi trẻ được. Muốn tươi trẻ thì phải sống lành mạnh vui vẻ, nhờ vui nên mới tươi, mà vui thì không giận. Vậy, nếu có ai lỡ làm phiền thì hoan hỷ bỏ qua, đó là tạo nhân tươi trẻ. Bằng ngược lại, cứ buồn giận, hết phiền người này, ghét người kia. Mà giận ghét thì lòng đâu có an ổn, nhẹ nhàng. Ăn không ngon, ngủ không được, đó là cái nhân bệnh hoạn làm cho thân mình tiều tụy, hốc hác.  

Nếu biết nhân xấu đưa tới quả xấu thì tránh, đừng muốn một đàng mà làm một nẻo thì không được như ý. Vậy, biết tu một ngày là làm cho mình được an vui một ngày, tu một năm là làm cho mình được an vui một năm và đồng thời cũng gây niềm vui cho mọi người. Hiểu như vậy chúng ta mới thấy nhân quả giúp chúng ta nhìn đúng lẽ thật, sống an lành, trở thành người gan dạ, mạnh mẽ không nhát nhúa, yếu đuối.  

Ví dụ, có một Phật tử vì không điều phục được cơn phiền giận nên lỡ đánh chửi người. Khi đánh chửi xong biết mình tạo nhân ác, chắc chắn là quả báo xấu sẽ đến. Nên khi bị người uy hiếp đánh đập lại thì gan dạ chịu chớ không kêu than hay trách cứ ai cả. Ngược lại, có người khi đánh chửi thì hăng hái, đến khi bị uy hiếp thì kêu trời kêu đất than trách đủ điều. Đó là người yếu đuối không thấy được nhân xấu mà mình đã tạo. Vậy muốn được an vui thì phải gan dạ bỏ những cái nhân xấu mà tạo nhân lành. Thường tạo nhân lành thì cái xấu ác sẽ yếu dần và hết hẳn.  
  
Hiểu được lý nhân quả thì đối với những sự việc bất tường xảy ra, chúng ta sẽ không trách người mà tự trách mình. Do mình trước kia mê muội không tránh nhân xấu ác nên giờ này thọ quả xấu. Sẵn sàng đón nhận một cách gan dạ bình tĩnh. Chúng ta thường thấy trong một gia đình hai ba chị em sống chung, có một người lỡ làm bể một cái tô hay cái dĩa, sợ bị rầy nên phi tang. Đến khi má hay ba hỏi không ai nhận là mình làm bể, thái độ như thế là nhát nhúa không có tinh thần trách nhiệm. Lỡ làm thì gan dạ thú nhận lỗi của mình để người khác không bị hàm oan, không bị vạ lây bởi cái dở của mình. Lý nhân quả giúp con người có tinh thần trách nhiệm, sáng suốt, biết lựa chọn nhân tốt để làm, nhân xấu để tránh. Và lỡ tạo nhân xấu rồi, thì sẵn sàng chấp nhận quả xấu một cách gan dạ không sợ sệt, không lẩn trốn. Vì không hiểu lý nhân quả nên mới nhát nhúa, sợ sệt, không có chánh tín, rồi làm xằng bậy sẽ đi vào con đường tà một cách dễ dàng.  
  
Hiện tại có một số Phật tử có cái lệ đầu năm đi chùa hái lộc, hay đi cúng thập tự để cầu cho trọn năm được bình an. Nhưng nếu nửa năm có xảy ra hoạn nạn thì thắc mắc tại sao mình đi cúng thập tự và đã cầu an mà vẫn còn hoạn nạn. Rồi cho rằng chùa cầu nguyện không linh, định năm sau sẽ không đi cúng chùa nữa. Quan niệm như vậy là không chánh đáng. Vì đi cúng chùa cầu xin Phật ban phước lành, đó chỉ là một ảo tưởng. Phật có bao giờ ban phước giáng họa cho ai đâu? Phật chỉ dạy cho ta việc nào để làm cho được an vui, việc nào nên tránh để khỏi bị khổ. Chúng ta nghe lời dạy của Ngài thực hành theo mới hết khổ. Phật không phải là một thần linh để ta tôn thờ lễ lạy và cầu xin phước lộc.  
  
Năm rồi có một Phật tử hỏi tôi:  
  
\-Thưa thầy, có người nói bà Chúa Xứ ở Châu Đốc linh lắm. Đến miếu bà vay tiền về làm ăn sẽ phát đạt. Theo thầy thì quan niệm đó đúng hay sai?  
  
Tôi đáp:  
  
\- Nếu vay tiền ở miếu bà về làm ăn phát tài thì mọi người ở Châu Đốc đều giàu hết, vì ở đó gần, họ sẽ vay để làm giàu. Nhưng có nhiều gia đình ở chung quanh miếu bà, nhà còn lụp xụp có vẻ nghèo khó, họ dại gì không vô miếu vay mà làm giàu, để quý vị từ phương xa đến vay?  
  
Đó là một chuyện vô lý, vậy mà người ta vẫn cứ tin, tin một cách mù quáng. Người Phật tử không thấy được lẽ thật, tin hết chỗ này linh đến chỗ khác linh, đua nhau đi tìm sự linh hiển ở bên ngoài. Không thấy được linh hay không linh là cái nhân tốt hay xấu mà mình đã tạo. Tạo nhân tốt thì gặp quả tốt, tạo nhân xấu thì gặp quả xấu. Điều đó quá rõ ràng, vì chúng ta chưa định tĩnh nên không thấy đó vậy.  
  
Lại có người hỏi:  
  
\- Thưa thầy, nhiều người đi biển gặp sóng to gió lớn, họ niệm Bồ Tát Quan Thế Âm, thấy Bồ Tát đến cứu họ được thoát nạn, họ cho rằng Bồ Tát linh thiêng. Theo thầy thì sự kiện đó như thế nào?  
  
Tôi đáp: Đã là Phật tử đi sông đi biển gặp sóng gió thì không ai tiếc hơi mà không niệm Quán Thế Âm Bồ Tát. Nhưng tại sao có người được cứu, vẫn có người bị chết chìm? Có phải Bồ Tát Quán Thế Âm thương người này mà không thương người kia không?  
  
Vì không hiểu lý nhân quả nên cho rằng người không bị nạn là nhờ niệm Bồ Tát. Bồ Tát linh giải cứu cho thoát nạn. Còn người bị nạn niệm Bồ Tát, mà Bồ Tát không linh nên không cứu. Tại sao đồng niệm Bồ Tát mà người niệm linh, người niệm không linh, làm sao cho rõ lẽ này? Người niệm danh hiệu Bồ Tát mà được thoát là vì chính người đó có nhiều nhân lành, nhiều phước đức. Nên khi tâm khởi tưởng Phật, tưởng Bồ Tát thì thấy Phật và Bồ Tát hiện. Vì chủng nghiệp lành đã huân chứa sẵn, đủ duyên liền khởi hiện hành *(thấy Phật, thấy Bồ Tát)*. Và vì do tích chứa nhiều nghiệp lành thì làm sao thọ quả khổ được.  

Còn người niệm danh hiệu Bồ Tát mà vẫn bị nạn, chính vì người đó thiếu phước, không có tích lũy nghiệp lành *(chủng tử Phật, Bồ Tát không có sẵn)*. Tuy có khởi niệm mà Phật và Bồ Tát vẫn không hiện. Và vì nhân ác đã có sẵn nên chiêu quả không lành. Để thấy, sự kiện trên cũng do nhân lành hay dữ mà chúng ta tạo, không phải do từ Phật hay Bồ Tát linh thiêng đến giúp. Thế nên, người Phật tử tu hành đầu tiên là phải hiểu lý nhân quả. Biết nhân nào nên làm, nhân nào nên tránh, đó là chúng ta tiến vào con đường giác. Mà người sống có tỉnh, có giác thì hết khổ được vui, rõ ràng không nghi ngờ.  
  
Hằng ngày, trong công việc làm ăn, tuy có bận rộn giao tế nhiều với mọi người, nhưng nếu chúng ta biết tránh nhân dữ, chọn nhân lành, thì từ ý nghĩ, lời nói, việc làm lúc nào cũng lương thiện, vừa lợi mình, vừa lợi người, đó là chúng ta đã tu. Chúng ta phải thường xuyên tu, tu từng phút, từng giờ, tu cả ngày... chớ đâu phải đợi tới giờ tụng kinh lạy Phật mới tu. Ngoài giờ đó, nếu có ai đụng chạm đến là ăn thua đủ, tu như vậy là không hiền. Lạy Phật thì lạy, tụng kinh thì tụng, chửi lộn vẫn cứ chửi, đánh lộn cũng dám đánh. Thế nên tu mà không hết khổ lỗi tại chỗ đó. Vì tu mà chỉ biết tu với Phật không chịu tu với chúng sanh, cũng không chịu tu với chính mình nữa. Phật đâu có cần chúng ta tu với Ngài, vậy mà cứ nghiêm trang lễ bái Phật, còn ra ngoài đời với mọi người thì không nhịn một lời, không nhường một bước, ăn thua đủ. Đối với Phật, dù quý vị có khen hay chê, Ngài cũng không vui không buồn, cũng không nói một lời. Ngài cũng không cần chúng ta tu với Ngài.  
  
Còn chúng sanh thì dễ buồn giận, nên chúng ta mới tu với họ thì mình bớt khổ mà họ cũng bớt khổ. Biết tu với nhau là đem lại hạnh phúc cho nhau, đem sự bình an lại cho nhau. Phật dạy chúng ta tu là tu với mọi loài, chớ đâu có bảo tu với Ngài. Vậy mà đa số người chỉ biết tu với Phật, ngày ngày lễ bái Phật, dâng hương dâng hoa cúng Phật...  
  
Thậm chí có nhiều người nói hôm nay là ngày tôi ăn chay nên tôi tu, đợi ăn chay mới tu. Vậy những ngày ăn mặn không tu sao? Một tháng ăn chay có bốn ngày hoặc sáu ngày nên chỉ tu có bốn ngày hoặc sáu ngày, còn lại hai mươi bốn ngày hoặc hai mươi sáu ngày cứ tự do làm ác với mọi người sao?  
  
Nếu đợi đến trước tượng Phật mới tu, đợi tụng kinh mới tu, đợi ăn chay mới tu, tu như thế thì quá hạn chế. Tu là phải thường xuyên nhìn thấy từng hành động, từng lời nói, từng ý nghĩ của mình, nếu tốt thì cho ra, xấu thì dừng lại, đó mới thật là tu. Tu như vậy mới đúng với tinh thần *"Bồ Tát Sợ Nhân"* và dù không muốn làm Bồ Tát thì quý vị cũng là Bồ Tát. Vì đã thực hành cái hạnh Bồ Tát ắt hẳn phải là Bồ Tát. Bồ Tát là giác, biết được nhân xấu không làm, nhân tốt thì làm, đó là tỉnh giác. Mà người hằng tỉnh, hằng giác không phải là Bồ Tát là gì?  
  
Các Phật tử ở đây đều thuộc câu *"Bồ Tát sợ nhân, chúng sanh sợ quả"*. Vậy ai cũng biết việc nào nên làm, việc nào nên tránh rồi. Tôi mong rằng quý vị cố gắng tu hành để tương lai sẽ thành Bồ Tát, tập sống với quan niệm Bồ Tát, hành động theo Bồ Tát thì mai kia chúng ta sẽ là Bồ Tát. Còn nếu cứ sống theo quan niệm và hành động của phàm phu thì suốt kiếp chúng ta vẫn là phàm phu. Vậy, phàm phu và Bồ Tát không xa, chỉ có mê hay giác mà thôi. Nếu giác là Bồ Tát và được an vui, nếu mê là phàm phu và bị đau khổ.  
