# Tu có chuyển được nhân quả không? {- #tu-co-chuyen-duoc-nhan-qua-khong}

Từ lâu chúng ta thường nghe nói gieo nhân nào thì chịu quả nấy, tức là ai tạo nhân gì thì phải thọ quả báo đúng như vậy không sai. Song, trong kinh Phật có dạy như vậy không? Đây là điều mà chúng ta phải tìm hiểu cho tường tận. Vì đa số người mới tu đều nghĩ rằng: Xưa kia làm điều tội ác, ngày nay tu hành là mong giảm bớt khổ đau.  

Nhưng nếu trước đã gây nhân nào sau phải chịu quả nấy thì tu để làm gì? Tu cốt cho hết khổ, mà nếu gây nhân nào phải thọ nhận quả nấy thì tu đâu có hết khổ? Nếu chúng ta hiểu theo nghĩa nông cạn, đơn giản là tác nhân nào thọ quả nấy thì sẽ thối tâm không tu được. Lý nhân quả của đạo Phật không cố định là tác nhân nào thọ quả nấy, mà cũng không phải tác nhân mà không thọ quả, nó rất phức tạp.  
  
Kinh A Hàm, Phật có dạy: **Người gây nhân bất thiện, trước hoặc sau họ biết tu thân, tu giới, tu tâm thì quả sẽ đổi thay. Nếu người gây nhân bất thiện mà không biết tu thân, tu giới, tu tâm thì gây nhân nào sẽ thọ quả nấy. Đó là nhân nào quả nấy và gây nhân mà biết chuyển nghiệp thì quả cũng đổi thay.**  
  
Phật có ví dụ một nắm muối, nếu hòa tan trong tô nước lạnh thì tô nước ấy mặn không uống được. Cũng nắm muối đó, nếu hòa tan trong lu nước lớn dung lượng độ vài ba trăm lít thì nước trong lu sẽ uống được, nhưng vị nước hơi mặn mặn. Và nếu nắm muối đó hòa tan trong một hồ nước dung tích bốn năm ngàn lít, nước không còn mặn, dùng xài bình thường.  

Nhân bất thiện là dụ cho vị mặn của nắm muối hòa tan trong tô nước thì quả cũng mặn không giải khát được. Nếu nhân mặn của mắm muối hòa tan trong lu nước thì quả mặn loãng ra, nước có thể tạm giải khát được. Nếu nhân mặn của mắm muối hòa tan trong hồ nước lớn, thì quả mặn không thấm vào đâu, nước dùng xài bình thường.  
  
Cũng vậy, người mà không biết tu thân, tu giới, tu tâm tạo nhân ác thì trả quả ác nguyên vẹn dụ như nắm muối tan trong tô nước, không giải khát được. Nếu người biết tu thân, tu giới thì dụ như nắm muối tan trong lu nước, tuy vị nước mặn nhưng cũng tạm dùng được. Còn người biết tu thân, tu giới, tu tâm dụ như nắm muối tan trong hồ nước to, vị nước không mặn, dùng xài bình thường.  

Vậy, nếu tu thân, tu giới, tu tâm thì nghiệp quả sẽ chuyển, không thọ đúng như khi gây nhân. Như vậy, nếu gây nhân ác mà không biết tu, không chuyển nghiệp thì tác nhân nào thọ quả ấy không sai chạy. Nếu gây nhân ác biết tu thân, tu giới là có chuyển nghiệp thọ quả báo nhẹ hơn. Còn gây nhân ác biết tu thân, tu giới, tu tâm gần như chuyển hoàn toàn. Cho nên tu là chuyển đau khổ được an vui.  
  
Kiểm lại, chúng ta từ nhỏ đến già, không ai là người hoàn toàn thiện lành, cũng có lúc người này làm người kia khóc than, cũng có lúc người kia làm người nọ oán hận. Như vậy, là đã tạo nhân xấu. Nếu hiện tại tu mà vẫn trả quả xấu như cũ thì tu có lợi ích gì? Thế nên phải biết, tu là chuyển quả xấu, tuỳ theo sức huân tu nhiều hay ít mà quả tuỳ theo đó chuyển đổi.  
  
Sau đây, Phật dạy: Có một gia chủ nuôi một bầy dê. Một hôm có người thường dân tới trộm dê, bị gia chủ bắt được đánh, đưa ra pháp luật bỏ tù. Lần khác, kẻ trộm dê là người của quan lớn sai tới, gia chủ chỉ bực tức nói năng đôi lời chớ không đối xử thậm tệ như người thường dân trước. Kế tiếp, kẻ trộm dê do lính của vua sai đến, thì gia chủ không dám nói nặng nhẹ gì cả mà chỉ van xin năn nỉ đừng bắt dê. Trong ba trường hợp trên chứng minh rằng: Người không biết tu thân, tu giới, tu tâm gây nhân bao nhiêu thì phải trả quả bấy nhiêu. Vì vậy mà nói nhân nào quả nấy, đó là dụ người thường dân trộm dê không thế lực.  
  
Trường hợp người trộm dê là lính của quan thì chỉ bị trách móc nặng nhẹ. Đó là dụ cho người biết tu thân, tu giới, tuy có tạo nhân ác nhưng thọ quả báo nhẹ hơn.  
  
Trường hợp người trộm dê là lính của vua, thì không bị đánh đập, không bị nói nặng nhẹ. Đó là dụ cho người tuy có tạo nhân ác nhưng biết tu thân, tu giới, tu tâm thì nghiệp quả được hoá giải.  
  
Như vậy để thấy cùng tạo nhân ác, tùy theo khả năng tu tập cao thấp mà thọ quả sai khác. Nếu biết tu thì quả liền chuyển, không cố định như người không biết tu. Khi biết rõ người có tu thân, tu giới, tu tâm thì sẽ thoát được những nghiệp quả đã gây trước kia; tuy nói thoát mà không phải hết hoàn toàn. Nghĩa là nắm muối vẫn hòa tan trong hồ nước, song vì nước trong hồ quá nhiều nên không thấy mặn.  
  
Cũng như chú lính của nhà vua trộm dê, tuy chủ dê không đánh đập không nói nặng nhẹ, nhưng trong lòng chủ nhà không vui, không cảm tình. Đó là nhân quả sai biệt theo khả năng tu tập.  
  
Thế nào là tu thân, tu giới, tu tâm?  
  
Tu thân là nơi thân này không làm điều ác, tất cả mọi điều ác dù lớn hay nhỏ đều phải tránh. Còn mọi điều thiện phải cố gắng làm, luôn luôn nhớ và làm đó là biết tu thân.  
  
Tu giới là Phật tử tại gia, sau khi quy y rồi, Phật dạy phải giữ năm giới:  
  
**1/ Không sát sanh:** Là không được giết người. Vì ai cũng muốn sống thì mạng sống phải được tôn trọng, không nên giết mạng sống của người. Nếu giết mạng sống của người thì bị luật pháp trừng trị. Vì tôn trọng mạng sống của mình nên phải tôn trọng mạng sống của người. Đó là lẽ công bằng, trái với lẽ công bằng là tội lỗi.  
  
Ngoài ra, đối với những con vật lớn như trâu bò heo chó, tránh được bao nhiêu là tốt bấy nhiêu. Chủ yếu là không giết người.  
  
Một là tự tay mình giết. Ví dụ mình oán thù ai thì tự mình đến giết người đó chết.  
  
Hai là sai bảo người khác giết. Ví dụ mình oán thù người nào, mình không trực tiếp giết được bèn xúi bảo hay mướn người khác giết.  
  
Ba là hoan hỷ khi nghe thấy giết. Ví dụ mình oán thù người nào đó tự mình không giết được, khi thấy nghe người đó bị giết, mình vui mừng thích thú.  
  
Như thế là phạm tội sát sanh. Vì tự tay giết là thân tạo nghiệp ác, sai bảo người giết là miệng tạo nghiệp ác, nghe thấy người giết sanh tâm vui mừng là ý tạo nghiệp ác, nên Phật cấm không cho Phật tử làm.  
  
**2/ Không được trộm cướp:** Phàm của cải của người khác, chẳng được không cho mà lấy từ một cây kim, một ngọn cỏ cũng vậy, tất cả các vật chẳng được không cho mà lấy. Hoặc trộm lấy, hoặc cướp giật, hoặc lừa gạt mà lấy, cho đến trốn xâu lậu thuế cũng đều gọi là trộm cắp.  
  
**3/ Không tà dâm:** Người Phật tử sau khi lập gia đình có đôi bạn rồi mà mình còn đi ngoại tình với người khác là phạm tội tà dâm. Vì đó là duyên cớ làm cho gia đình mất hạnh phúc, làm cho gia đình tan vỡ, là cái nhân gây đau khổ cho mình cho người, vì vậy mà Phật cấm.  
  
**4/ Không nói dối:** Nói dối có bốn trường hợp phạm tội.  
  
- Chuyện có nói không, chuyện không nói có, cốt lừa gạt để lấy tiền, lấy của người.  
- Nổi giận nói lời hung dữ, thô ác mắng chửi người, vu oan người.  
- Dùng lời hoa mỹ văn chương thêu dệt để lừa gạt người.  
- Nói đâm thọc làm cho đôi bên bất hòa thù oán nhau.  
  
Đó là những trường hợp nói dối thì phạm tội. Nếu nói dối để cười cho vui, hoặc để trấn an người bệnh người khổ, hoặc để cứu mạng người thì không phạm.  
  
**5/ Không uống rượu:** Nói đơn giản là rượu, ngoài ra các thứ như á phiện, xì ke, ma túy đều không được dùng. Vì nó là cái nhân sanh ra bệnh hoạn, làm cho tiêu tán tài sản, mất hết trí tuệ. Nhưng, nếu vì lý do đau bệnh, cần phải uống thuốc rượu để trị bệnh thì được phép uống.  
  
Phật dạy giữ năm giới là vì lòng từ bi, sợ chúng sanh vi phạm thì bị đau khổ. Nên giữ gìn không phạm thì được an vui. Đó là tu giới.  
  
Tu tâm là tu thế nào?  
  
Tâm là chỉ cho mọi ý niệm xấu ác như tham, sân, si... Tu tâm là bỏ được lòng tham lam, tính sân hận, đố kỵ, si mê... Tham thì ai cũng có, và có nhiều loại như tham danh, tham lợi, tham tài, tham sắc, tham ăn, tham ngủ... Ở đây tôi chỉ đề cập tham ăn và tham ngủ, được mọi người coi là nhỏ mọn, song muốn bỏ không phải là dễ. Ăn nếu dở quá thì không vui, nếu không no thì cũng không được; ăn thì muốn cho ngon, cho no đủ. Ngủ thì phải ngủ cho đủ giấc, nếu bắt dậy sớm thì không vui. Vì vậy, chúng ta lúc nào cũng kẹt trong vòng tham muốn, mà đó là cái bệnh chung của mọi người, không ai là không có. Tu là dẹp bỏ lòng tham, còn sân và si luôn luôn đi chung, hễ có sân là có si.  
  
Thuở xưa có một gia đình gồm có ba người, người con đi làm ngoài đồng, ông nội và cháu ở nhà, ông đưa cho cháu hai cái tô và hai đồng bảo:  
  
\- Cháu hãy đi mua một đồng tương và một đồng chao.  
  
Đứa cháu cầm tô và tiền đi một lúc về hỏi:  
  
\- Thưa ông nội, đồng nào mua tương đồng nào mua chao?  
  
Ông rầy cho nó một hồi, rồi bảo:  
  
\- Đồng nào mua cũng được.  
  
Nó liền chạy đi, một lúc lâu trở về hỏi:  
  
\- Thưa ông nội, hai cái tô cái nào đựng tương cái nào đựng chao?  
  
Ông giận quá tát cho nó mấy tát tai, nó khóc lu bù. Ngay khi đó, người con đi cày về, tay cầm cây roi đánh trâu. Thấy con mình bị ông già đánh, nó la khóc nên nổi giận nói:  
  
\- Ông đánh con tôi, tôi đánh con ông cho ông biết.  
  
Người con liền cầm roi tự quất lên mình túi bụi, ông già nóng ruột quá nói:  
  
\- Mày đánh con tao, tao treo cổ cha mày cho mày biết.  
  
Ông liền làm vòng, đút đầu vô treo cổ.  
  
Kết luận câu chuyện, quý vị thấy gia đình đó si mê ở mức độ nào? Nếu nói ngu thì gia đình đó không ai bằng. Đứa cháu đã ngu, người cha còn ngu hơn, đến ông nội lại quá ngu! Ngu là do nổi giận mà ra vậy. Nên có sân là có si, làm mà không biết sai, không biết hại.  

Xét lại xem, chúng ta có làm những chuyện na ná như vậy không? Tưởng chừng như không, nhưng khi có làm mà không hay. Chẳng hạn lúc nào đó, con làm trái ý, cha mẹ nổi giận chửi "Mày là đồ trâu đồ chó..." Nếu có người hỏi "Nó là trâu là chó, vậy cha mẹ nó là gì?". Làm cha mẹ chửi con như vậy có khôn không? Thế mà có lắm người chửi như vậy! Nên biết, hễ nổi sân là liền ngu, không biết phải quấy. Tưởng nói cho đỡ bực, nhưng không ngờ tự ngầm nhận mình là trâu là chó. Vì con là trâu chó, cha mẹ đương nhiên phải là trâu chó mới sanh con trâu chó.  
  
Hoặc có người khi giận con thì chửi ông cố nội, ông cố ngoại nó... Ông cố nội, ông cố ngoại nó là ai? Là ông nội, ông ngoại mình. Vậy mà khi giận thì người ta cứ nói, cứ làm. Chẳng khác gì người kia đánh con ông già để cho ổng tức, nhưng tự đánh mình thì mình đau. Rồi ông già treo cổ cha nó, cho nó hoảng sợ, nhưng rồi chính ông chết!  
  
Vì sân si mà chúng ta không nhận biết điều phải lẽ trái, cứ làm bậy, nói bậy, khiến cho thiên hạ chê cười. Nên ca dao Việt Nam có câu:  
  
> Sân si nghiệp chướng không chừa,  
> Bo bo mà giữ tương dưa làm gì  
  
Tu mà không chịu bỏ tham, bỏ sân, bỏ si mà cứ khoe "tôi ăn chay một tháng mười ngày, 15 ngày v.v..." Ăn chay, ăn tương dưa là để chừa tham, sân, si. Có chừa bỏ được tham, sân, si thì tâm mới sáng suốt. Tâm sáng suốt thì không nói bậy, làm bậy. Không nói bậy, làm bậy thì nghiệp chướng theo đó mà giảm. Nếu không chừa bỏ tham, sân, si thì nghiệp chướng tội lỗi khó mà hết được.  
  
Tuy nói tu thân, tu tâm, nhưng chủ yếu là tu tâm. Nếu tu tâm mà được viên mãn thì mọi nghiệp chướng không còn, mọi họa khổ sẽ hết, không phải trả nặng nề như lúc gây tạo.  
  
Nói nhân nào quả nấy là chưa chính xác, chưa lột lý nhân quả, vì chỉ đúng một trường hợp là người không biết tu, còn đối với người biết tu thì không đúng.  
  
Nếu người tạo nghiệp ác nhiều, vì yếu đuối không cố gắng làm lành, chắc rằng nghiệp ác khó chuyển đổi. Ví dụ, có nhiều người lỡ nghiện rượu đều được bác sĩ và bạn tốt khuyên nên bỏ rượu, vì uống rượu hại sức khỏe, tinh thần không minh mẫn, tốn kém tiền bạc, vợ con khốn khổ, gia đình không hạnh phúc. Nghe lời khuyên, họ hiểu, thấy rõ uống rượu là tai hại. Nhưng có người không bỏ được, vì tâm hồn họ yếu đuối, bạc nhược. Lại có người ý chí mạnh mẽ biết uống rượu có hại dứt khoát bỏ ngay. Vậy, nghiệp cũng có thể chuyển được mà cũng có thể chuyển không được, tùy theo ý chí mạnh hay yếu của mọi người.  
  
Có nhiều Phật tử lấy làm thắc mắc hoặc nuối tiếc về những người tu xuất. Vì họ cho rằng các thầy, các cô có rất nhiều duyên phước mới được xuất gia tu hành. Tại sao có nhiều người tu mười mấy hai mươi năm học hành tương đối cũng thông, bỗng dưng cởi áo hoàn tục. Họ hỏi:  
  
\- Thầy tu ở trong đạo an ổn quá, tại sao lại hoàn tục cho phiền lụy?  
  
Các thầy trả lời chung chung:  
  
\- Tại nghiệp của tôi nó lôi.  
  
Quý vị nghĩ sao? Ai tu có nghiệp cũng bị nghiệp lôi hoàn tục hết, hay có người bị lôi có người chuyển nghiệp, đổi nghiệp? Nếu ai tu cũng bị nghiệp lôi hoàn tục, thì chắc chắn không có người tu tới nơi tới chốn. Chúng ta sanh ra trong đời này đều có liên hệ với quá khứ. Kẻ có nghiệp này, người có nghiệp khác. Song, tùy theo ý chí của mỗi người yếu hay mạnh mà chuyển được nghiệp hay không. Đừng đổ thừa nghiệp, để rồi tu, nếu gặp cảnh nghịch lòng, trái ý liền bỏ đạo về đời, lại nói do nghiệp lôi. Người như thế là người không ý chí, không gan dạ, tinh thần cầu tiến quá thấp.  

Tuy nhiên, chúng ta đừng khinh những người tu hoàn tục. Khi Phật còn tại thế, Tỳ Kheo Ni Liên Hoa Sắc chứng quả A La Hán, trên đường đi giáo hóa, bà gặp các cô gái trẻ, bà rủ:  
  
\- Các con nên xuất gia đi tu.  
  
Các cô thưa:  
  
\- Các con còn nhỏ dại, ham ăn, ham ngủ, tu không được.  
  
Bà nói:  
  
\- Không sao cứ đi tu.  
  
Các cô nói:  
  
\- Đi tu không làm tỳ kheo ni, lỡ tụi con phạm giới đọa địa ngục thì sao?  
  
\- Không sao, lỡ đọa địa ngục, hết quả báo trở lên tu tiếp.  
  
Theo Bà Liên Hoa Sắc thì nếu tu phạm giới bị đọa hết quả báo thì trở lại tu nữa, vì chủng tử tu hành vẫn còn, gặp duyên thì nhớ lại. Nếu người chưa tu lỡ tạo nghiệp ác bị đọa, hết quả báo không có chủng tử cũ thì biết bao giờ mới tu được. Bây giờ, tuy người tu phạm giới bị đọa có thua kém những người tu khác, nhưng với người chưa tu vẫn có phần hơn, vì họ còn chủng tử cũ, đủ duyên họ phát tâm tu trở lại.  
  
Tới đây, tôi xin đi xa một chút là trình bày lý nhân quả theo tinh thần thiền tông. Trong *"Chứng Đạo Ca"* của Thiền Sư Huyền Giác có hai câu:  
  
> Liễu, tức nghiệp chướng bổn lai không,  
> Vị liễu, ưng tu hoàn túc trái  
  
Nếu liễu ngộ thì nghiệp chướng xưa nay là không, còn nếu chưa liễu ngộ thì phải đền nợ trước. Những nhân ác, những nghiệp bất thiện đã gây tạo từ trước, nếu tu hành không liễu ngộ thì phải trả đủ. Còn nếu tu mà liễu ngộ được thì nghiệp chướng cũ theo đó mà hóa giải không còn.  
  
Sau có một thiền khách tên Hạo Nguyệt đến Thiền Sư Trường Sa Cảnh Sầm hỏi rằng:  
  
\- Cổ Đức có nói: *"Liễu tức nghiệp chướng bổn lai không; vị liễu ưng tu hoàn túc trái"*. Như Tổ Sư Tử và Tổ Huệ Khả vì sao lại đền nợ trước?  
  
Trường Sa bảo:  
  
\- Đại đức chẳng biết bổn lai không.  
  
Hạo Nguyệt hỏi:  
  
\- Thế nào là bổn lai không?  
  
\- Nghiệp chướng.  
  
\- Thế nào là nghiệp chướng?  
  
\- Bổn lai không.  
  
Tại sao nói nghiệp chướng bổn lai không?  
  
Theo Phật giáo thì nghiệp là động lực chi phối đời sống con người từ đời trước cho tới đời này và mãi về sau. Nếu con người còn tạo nghiệp thì còn trôi lăn trong vòng luân hồi sanh tử. Song, dùng trí quan sát cho kỹ thì nghiệp không thật. Ví dụ ông A nói lời hung ác *(khẩu nghiệp)* làm cho ông B buồn giận, sau ông A hối hận ăn năn xin lỗi ông B, ông B vui vẻ tha thứ. Khẩu nghiệp ác của ông A trước làm cho ông B buồn giận, sau hối hận xin lỗi thì ông B hết buồn giận. Như vậy, nghiệp ác thật thì không đổ được, vì nó không thật nên chuyển được. Nghiệp còn là khi tâm chúng ta mê, nếu biết thức tỉnh chuyển nó thì nó hết, nên nói nghiệp vốn không thật. Tuy không thật, nhưng nếu chúng ta mê thì nó kéo đi mãi trong vòng luân hồi sanh tử không dừng.  
  
Đã nói *"Nghiệp chướng bổn lai không"* tại sao Tổ Sư Tử bị hành hình, Tổ Huệ Khả chết trong tù? Trong kinh, Phật nói có nhân là có quả, nhưng quả đến còn tùy theo sức tu cao thấp mà chuyển. Tổ Sư Tử khi tới nước Kế Tân giáo hóa, bị ngoại đạo sàm tấu Ngài truyền bá tà đạo nên vua tức giận đích thân cầm gươm đến chỗ ngài hỏi:  
  
\- Thầy được không tướng chưa?  
  
\- Đã được.  
  
\- Đã được thì còn sợ chết chăng?  
  
\- Đã lìa sống chết thì đâu có sợ.  
  
\- Chẳng sợ thì có thể cho trẫm cái đầu chăng?  
  
\- Thân chẳng phải của ta, huống nữa là cái đầu.  
  
Vua liền chặt đầu ngài rơi xuống đất.  
  
Với con mắt phàm phu thì thấy ngài bị trả quả chặt đầu. Nhưng dưới con mắt liễu ngộ của ngài thì thấy năm uẩn là không thật, năm uẩn còn mất là trò chơi, nên Ngài không tiếc cái đầu thì có gì gọi là trả? Sở dĩ chúng ta thấy ngài trả nghiệp là vì chúng ta chưa liễu ngộ, còn thấy năm uẩn thật.  
  
Tổ Huệ Khả cũng vậy, khi Ngài ngộ đạo ở Tổ Bồ Đề Đạt Ma, sau Ngài truyền tâm ấn cho Tổ Tăng Xán. Ngài nói: *"Ta còn chút duyên để đi trong nhân gian"*. Rồi Ngài Đến giáo hóa ở một vùng nọ cũng bị người sàm tấu Ngài là người truyền đạo không đúng chánh pháp, quan địa phương bắt giam Ngài. Khi bị giam trong khám, Ngài chỉ cười mà không buồn. Ngài nói duyên ta hết ở đây, rồi Ngài tịch ở trong khám.  
  
Đối với chúng ta khi bị nhốt trong khám, thấy đó là một hình phạt rất khổ đau. Nhưng đối với Ngài, Ngài không thấy có những sự kiện bực bội, đớn đau, nên Ngài cười. Như vậy, ở tù mà không thấy ở tù, chết trong khám mà không thấy chết trong khám, đó là do Ngài liễu đạo. Cái quả mà chúng ta thấy Ngài trả, nhưng đối với Ngài thì không có trả.  
  
Tôi lấy một ví dụ thực tế cho dễ hiểu. Ông Tần thuở xưa chửi bới làm ông Tấn tức giận. Nhưng vì ông Tấn yếu thế nên ôm hận không dám trả lời. Sau ông Tấn có cơ hội trả thù ông Tần, ông Tần đã biết tu và ngộ đạo, khi bị ông Tấn chửi, ông Tần chì cười mà không giận. Hồi xưa ông chửi thì ông Tấn giận, nay ông Tấn chửi thì ông Tần cười. Vậy ông Tần có trả quả không? Người không tu thấy ông Tần bị chửi, cho là ông Tần trả quả. Nhưng với ông Tần là người liễu đạo, nghe tiếng chửi như gió thoảng ngài tai, qua rồi thì mất, nên cười mà không buồn. Vậy, dù cho nghiệp chướng xảy ra người đời thấy kinh hoàng khủng khiếp nên thấy có trả, nhưng đối với người liễu đạo thì không có giá trị, nên thấy không có trả.  
  
Thế nên, chư Tổ không thấy trả nghiệp mà người phàm tục thì thấy có trả nghiệp. Để thấy, chúng ta tu từ thấp là giữ năm giới, thân không làm ác là đã chuyển được bao nhiêu thứ khổ đau rồi. Nếu tu tiến hơn nữa là bỏ tham lam, sân giận, si mê. Tham, sân, si càng ít, tâm càng trong sáng, càng thanh thoát, do đó mà được an vui. Và nếu tu tới chỗ viên mãn thì mọi nghiệp chướng đối với mình coi như không có. Nếu không bị nghiệp chi phối làm cho đau khổ thì không giải thoát là gì?  
  
Hiện nay có một số Phật tử mê tín quan niệm sai lầm, cho rằng tụng kinh Kim Cang, tụng kinh Pháp Hoa đổ nghiệp. Do tu, do tụng kinh nên xẩy ra nhiều tai nạn... Vậy nghiệp đó đổ bằng cách nào? Do tụng kinh nghiệp nó tràn ra, hay do xưa kia tạo nhiều nghiệp ác bây giờ đổ bớt đi??? Đã là Phật tử tại sao không tìm hiểu nghiệp đổ bằng cách nào, mà chỉ nghe nói đổ nghiệp là không dám tụng kinh nữa. Học đạo như vậy quá sai lầm, tu là để chuyển nghiệp, giảm nghiệp, chuyển và giảm không có nghĩa là thêm, là đổ ra.  
  
Nếu xưa kia tạo nghiệp ác, đáng lý trả bằng sự đánh đập, hoặc trả bằng tai nạn mất nhân mạng, nhưng nhờ biết tu nên chỉ bị mắng chửi hay bị trộm cắp mất tiền của. Khi bị mắng chửi hay mất tiền của nên quán xét: có thể nghiệp chướng của mình phải trả bằng tai nạn nặng nề khổ đau hơn nhiều, nhờ biết tụng kinh nên được chuyển nghiệp chỉ bị mắng chửi mất tiền của thì quá tốt. Xét như vậy, thì sự tu học mới tiến bộ. Ngược lại, nghe nói đổ nghiệp cứ tin suông rồi hoảng sợ không tu nữa, là sai lầm.  
  
Lại có nhiều Phật tử quan niệm rằng đi chùa quy y biết tu rồi, thì kể từ đây về sau cuộc sống sẽ bình an không có gì trở ngại. Tu là phải hanh thông mọi việc, nếu có trục trặc thì thối chí, nản lòng không tu. Chúng ta nhớ, tu là bỏ ác làm lành, thì ở trong đời nếu có tai nạn xảy ra, biết đó là nghiệp quá khứ còn rơi rớt lại, không sợ hãi, không thối chí, vững lòng tin mà tiến tu không thối chuyển.  
  
Đừng nghĩ tu là mọi nghiệp xấu sạch hết, mọi việc xảy ra đều như ý.  
  
Chính Đức Phật là người tu hành công đức viên mãn, thế mà Ngài còn gặp những cái khó khăn nguy hiểm. Có lần Ngài đi giáo hóa ở một làng Bà La Môn, gia đình nọ giỏi về tướng số, sanh được một người con gái rất đẹp. Ông Bà La Môn này muốn gả con gái ông cho người có đủ ba muơi hai tướng tốt, nhưng tìm mãi chưa được. Bỗng một hôm tình cờ ông gặp Phật đang đi giáo hóa, ông mừng quá chạy về nhà kêu vợ ra xem. Bà ra thấy Phật rất hài lòng, đúng là đủ ba mươi hai tướng tốt, bà bèn ngỏ ý gả con gái cho Ngài.  
  
Phật nói: *"Đối với bà thì con gái bà đẹp, song, đối với ta đó là một dãy da hôi thúi, tất cả trong thân nàng đều là bất tịnh"*. Nghe Phật đáp, bà buồn, trở về nhà thuật lại câu chuyện cho con gái nghe. Cô tự ái nổi giận, ôm lòng thù oán thề rằng sẽ trả thù Phật.  
  
Sau cô được làm hoàng hậu của một nước. Bấy giờ, Phật đến giáo hóa ở xứ đó, hoàng hậu bèn tập hợp du đãng chặn đường Phật để mắng chửi. Tôn Giả A Nan đi theo Phật, thấy du đãng vây mắng thậm tệ, ngài không chịu nổi, mới nói:  
  
\- Bạch Thế Tôn, xin Thế Tôn đi nước khác giáo hóa.  
  
Phật hỏi:  
  
\- Đi đâu?  
  
A Nan thưa:  
  
\- Thế Tôn đi nước nào cũng được, vì ở nước này cứ bị người vây chửi, con không cam chịu được.  
  
Phật hỏi:  
  
\- Giả sử đi tới chỗ khác bị người ta chửi nữa thì A Nan tính sao?  
  
A Nan thưa:  
  
\- Nếu tới đó mà bị chửi nữa thì chúng ta về nước Xá Vệ, Ma Kiệt Đà... chỗ mà Thế Tôn có nhiều đệ tử ở đó giáo hóa.  
  
Phật hỏi:  
  
\- Nếu là thầy thuốc giỏi, A Nan có nên đề bảng: *"Tôi chỉ trị những bệnh nhẹ, không trị những bệnh nặng"* chăng?  
  
A Nan thưa:  
  
\- Bạch Thế Tôn, không được, thầy thuốc giỏi phải trị bệnh nặng mới cứu được nhiều người.  
  
Phật nói:  
  
\- Cũng vậy, dân ở đây họ nhiều mê muội như người bệnh nặng, nên gặp ta họ chửi. Thôi, thong thả, để ta giáo hóa họ, vì họ cần ta.  
  
Du đãng tiếp tục chửi Phật.  
  
A Nan nói:  
  
\- Họ cứ chửi Thế Tôn hoài, làm sao giáo hóa được?  
  
\- Chừng nào họ không nghe lời nói của ta thì ta đi.  
  
Nghe Phật trả lời A Nan như vậy, du đãng nói:  
  
\- Thôi, Cù Đàm ở đây giáo hóa, chúng tôi sẽ nghe lời Ngài dạy.  
  
Từ đó Phật nói pháp giáo hóa với họ.  
  
Quý vị thấy, Phật mà còn bị người chửi mắng huống là chúng ta. Nhưng điều quan trọng là Tôn Giả A Nan cũng như chúng ta còn tâm phàm, nên nghe chửi không chịu được. Còn Phật đã giác ngộ, tiếng chửi đối với Ngài như gió thoảng ngoài tai. Ngài không động tâm, nên thương họ là những người mê muội bệnh nặng, nên nói pháp cứu chữa.  
  
Cũng vậy, chúng ta khi phát tâm tu, nếu gặp người làm khó không nên buồn giận mà phải quán khởi lòng thương và cảm hóa họ. Nhất là những Phật tử có gia đình mà biết tu, hoặc bị chồng hay vợ, hay con làm khó dễ, đó là cơ hội tốt để mình tu. Chớ buồn giận và đừng cho rằng bạn mình, con mình phá rối không cho mình tu. Mà nên xét nghĩ thương bạn, thương con, vì chưa hiểu đạo còn mờ tối nên cần sự cảm hóa của mình.  
  
Thế nên, tất cả mọi khó khăn, những lời xúc não, nếu chúng ta biết tu, tâm sáng suốt hóa giải tất cả thì được an vui.  
  
Một lần khác Phật đi giáo hóa vùng Bà La Môn, các tu sĩ Bà La Môn thấy đệ tử của mình theo Phật nhiều quá, nên ra đón đường Phật chửi. Phật vẫn thong thả đi, họ đi theo sau chửi. Thấy Phật thản nhiên làm thinh, họ tức, chặn Phật lại hỏi:  
  
\- Cù Đàm có điếc không?  
  
\- Ta không điếc.  
  
\- Ngài không điếc tại sao không nghe tôi chửi?  
  
\- Này Bà La Môn, nếu nhà ông có đám tiệc, thân nhân tới dự, mãn tiệc họ ra về, ông lấy quà tặng, họ không nhận thì quà ấy về ai?  
  
\- Quà ấy về tôi chứ ai.  
  
\- Cũng vậy, ông chửi ta, ta không nhận thì thôi.  
  
Người kêu tên Phật chửi mà Ngài không nhận. Còn chúng ta, những lời nói bóng nói gió ở đâu đâu cũng lắng nghe để buồn để giận. Như vậy mới thấy những lời cuồng dại của chúng sanh Ngài không chấp, không buồn. Còn chúng ta do si mê, chỉ một lời nói nặng, nói hơn, ôm ấp mãi trong lòng, vì vậy mà khổ đau triền miên. Chúng ta tu là tập theo gương của Phật, mọi tật xấu của mình phải bỏ, những hành động lời nói không tốt của người đừng quan tâm, như thế mới được an vui.  
  
Trong kinh Phật ví dụ người ác mắng chửi người thiện, người thiện không nhận lời mắng chửi đó. Người ác giống như người ngửa mặt lên trời phun nước bọt, nước bọt không tới trời mà rơi xuống mặt người phun. Thế nên, có thọ nhận mới dính mắc khổ đau, không thọ nhận thì an vui hạnh phúc.  

Từ đây về sau, quý vị có ai nghe ai nói gì về mình dù tốt hay xấu, chớ nên thọ nhận thì sẽ được an vui. Đa số chúng ta có cái tật nghe người nói không tốt về mình qua miệng người thứ hai, thứ ba, thì tìm phăng ra manh mối để thọ nhận rồi nổi sân si phiền não. Đó là kẻ khờ, không phải người trí. Tuy có chướng duyên bên ngoài mà chúng ta biết giải, không thọ nhận, đó là tu. Không phải tu là cầu an suông, mà phải có người thử thách để có dịp coi lại mình đã làm chủ được mình chưa. Nếu còn buồn giận vì một vài lý do bất như ý bên ngoài đó là tu chưa tiến.  
  
Tinh thần nhân quả của đạo Phật không phải gây nhân nào chịu quả ấy trọn vẹn, ngoại trừ người không biết tu thì nhân quả không sai khác. Còn với người biết tu thì nhân quả biến chuyển theo công phu tu hành cao thấp mà có sai khác.  

Tu là chuyển nghiệp, giảm hết phiền não khổ đau để được an vui hạnh phúc, đó là tu đúng theo lời Phật dạy. Nếu tu sai thì không chuyển được nghiệp nên phiền lụy cứ dai dẳng khổ đau không dứt trừ, lại còn thối chí tu tập, không được lợi ích gì cả. Tôi mong rằng quý Phật tử sau khi nghe pháp nên nghiệm xét ứng dụng tu hành, để trên đường tu mỗi ngày mỗi tiến, cho hết khổ, được vui.  
